// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bank.proto

package zqbapis

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BankListResp struct {
	// 資料
	Data                 []*BankList `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BankListResp) Reset()         { *m = BankListResp{} }
func (m *BankListResp) String() string { return proto.CompactTextString(m) }
func (*BankListResp) ProtoMessage()    {}
func (*BankListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{0}
}
func (m *BankListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankListResp.Unmarshal(m, b)
}
func (m *BankListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankListResp.Marshal(b, m, deterministic)
}
func (m *BankListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankListResp.Merge(m, src)
}
func (m *BankListResp) XXX_Size() int {
	return xxx_messageInfo_BankListResp.Size(m)
}
func (m *BankListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BankListResp.DiscardUnknown(m)
}

var xxx_messageInfo_BankListResp proto.InternalMessageInfo

func (m *BankListResp) GetData() []*BankList {
	if m != nil {
		return m.Data
	}
	return nil
}

// 銀行列表
type BankList struct {
	// 銀行編號
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 名稱
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 圖片位置
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankList) Reset()         { *m = BankList{} }
func (m *BankList) String() string { return proto.CompactTextString(m) }
func (*BankList) ProtoMessage()    {}
func (*BankList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{1}
}
func (m *BankList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankList.Unmarshal(m, b)
}
func (m *BankList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankList.Marshal(b, m, deterministic)
}
func (m *BankList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankList.Merge(m, src)
}
func (m *BankList) XXX_Size() int {
	return xxx_messageInfo_BankList.Size(m)
}
func (m *BankList) XXX_DiscardUnknown() {
	xxx_messageInfo_BankList.DiscardUnknown(m)
}

var xxx_messageInfo_BankList proto.InternalMessageInfo

func (m *BankList) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *BankList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BankList) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func init() {
	proto.RegisterType((*BankListResp)(nil), "zqbapis.BankListResp")
	proto.RegisterType((*BankList)(nil), "zqbapis.BankList")
}

func init() { proto.RegisterFile("bank.proto", fileDescriptor_a6371916d5cb63b4) }

var fileDescriptor_a6371916d5cb63b4 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0xcc, 0xcb,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xaf, 0x2a, 0x4c, 0x4a, 0x2c, 0xc8, 0x2c, 0x56,
	0x32, 0xe5, 0xe2, 0x71, 0x4a, 0xcc, 0xcb, 0xf6, 0xc9, 0x2c, 0x2e, 0x09, 0x4a, 0x2d, 0x2e, 0x10,
	0x52, 0xe5, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd4,
	0x83, 0xaa, 0xd3, 0x83, 0x2b, 0x02, 0x4b, 0x2b, 0x79, 0x70, 0x71, 0xc0, 0x44, 0x84, 0x84, 0xb8,
	0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58,
	0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x44, 0x0c, 0xc4, 0x16, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x4d,
	0x4c, 0x4f, 0x95, 0x60, 0x06, 0x0b, 0x42, 0x38, 0x49, 0x6c, 0x60, 0x07, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x11, 0x89, 0xe1, 0xf2, 0x9e, 0x00, 0x00, 0x00,
}
