// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: captcha_geetest.proto

package zqbapis

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CaptchaGeeTestRegisterResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Gt                   string   `protobuf:"bytes,2,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge            string   `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	NewCaptcha           bool     `protobuf:"varint,4,opt,name=new_captcha,json=newCaptcha,proto3" json:"new_captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaGeeTestRegisterResp) Reset()         { *m = CaptchaGeeTestRegisterResp{} }
func (m *CaptchaGeeTestRegisterResp) String() string { return proto.CompactTextString(m) }
func (*CaptchaGeeTestRegisterResp) ProtoMessage()    {}
func (*CaptchaGeeTestRegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f70d14b818e52cc5, []int{0}
}
func (m *CaptchaGeeTestRegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaGeeTestRegisterResp.Unmarshal(m, b)
}
func (m *CaptchaGeeTestRegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaGeeTestRegisterResp.Marshal(b, m, deterministic)
}
func (m *CaptchaGeeTestRegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaGeeTestRegisterResp.Merge(m, src)
}
func (m *CaptchaGeeTestRegisterResp) XXX_Size() int {
	return xxx_messageInfo_CaptchaGeeTestRegisterResp.Size(m)
}
func (m *CaptchaGeeTestRegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaGeeTestRegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaGeeTestRegisterResp proto.InternalMessageInfo

func (m *CaptchaGeeTestRegisterResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CaptchaGeeTestRegisterResp) GetGt() string {
	if m != nil {
		return m.Gt
	}
	return ""
}

func (m *CaptchaGeeTestRegisterResp) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *CaptchaGeeTestRegisterResp) GetNewCaptcha() bool {
	if m != nil {
		return m.NewCaptcha
	}
	return false
}

func init() {
	proto.RegisterType((*CaptchaGeeTestRegisterResp)(nil), "zqbapis.CaptchaGeeTestRegisterResp")
}

func init() { proto.RegisterFile("captcha_geetest.proto", fileDescriptor_f70d14b818e52cc5) }

var fileDescriptor_f70d14b818e52cc5 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x14, 0x84, 0x49, 0x15, 0x6b, 0x9f, 0xe0, 0x10, 0x10, 0x82, 0x08, 0x16, 0xa7, 0x4e, 0x2e, 0xfe,
	0x04, 0x07, 0xf7, 0xe0, 0x5e, 0xd2, 0x70, 0xa4, 0x85, 0xd2, 0xc6, 0xbe, 0x27, 0x05, 0x77, 0xff,
	0xb7, 0x50, 0x2b, 0x8e, 0xf7, 0x71, 0xdc, 0x7d, 0xb4, 0xf3, 0x2e, 0x8a, 0xaf, 0x5d, 0x19, 0x00,
	0x01, 0xcb, 0x39, 0x0e, 0xbd, 0xf4, 0x3a, 0x7d, 0x3d, 0x2a, 0x17, 0x1b, 0x3e, 0xbd, 0x15, 0xed,
	0xaf, 0xdf, 0xca, 0x0d, 0xb8, 0x83, 0xc5, 0x22, 0x34, 0x2c, 0x18, 0x2c, 0x38, 0x6a, 0x43, 0x29,
	0x3f, 0xbd, 0x07, 0xb3, 0x51, 0xb9, 0x2a, 0xd6, 0xf6, 0x17, 0xf5, 0x96, 0x92, 0x20, 0x26, 0xc9,
	0x55, 0x91, 0xd9, 0x24, 0x88, 0x3e, 0x50, 0xe6, 0x6b, 0xd7, 0xb6, 0xe8, 0x02, 0xcc, 0x62, 0xc2,
	0x7f, 0xa0, 0x8f, 0xb4, 0xe9, 0x30, 0x96, 0xb3, 0x8c, 0x59, 0x4e, 0x5b, 0xd4, 0x61, 0x9c, 0xbf,
	0xab, 0xd5, 0xe4, 0x75, 0xf9, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x8b, 0xa8, 0x2f, 0xb0, 0x00,
	0x00, 0x00,
}
