// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package zqbapis

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status_Enum int32

const (
	// 失敗
	Status_failed Status_Enum = 0
	// 成功
	Status_success Status_Enum = 1
)

var Status_Enum_name = map[int32]string{
	0: "failed",
	1: "success",
}

var Status_Enum_value = map[string]int32{
	"failed":  0,
	"success": 1,
}

func (x Status_Enum) String() string {
	return proto.EnumName(Status_Enum_name, int32(x))
}

func (Status_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 0}
}

type Paging struct {
	// page index
	PageIndex int32 `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty" form:"page_index"`
	// page size
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"page_size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}
func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *Paging) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PagingResult struct {
	// page index
	PageIndex int32 `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	// page size
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 總頁數
	TotalPage int32 `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	// 總筆數
	TotalRow             int64    `protobuf:"varint,4,opt,name=total_row,json=totalRow,proto3" json:"total_row,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagingResult) Reset()         { *m = PagingResult{} }
func (m *PagingResult) String() string { return proto.CompactTextString(m) }
func (*PagingResult) ProtoMessage()    {}
func (*PagingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}
func (m *PagingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingResult.Unmarshal(m, b)
}
func (m *PagingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingResult.Marshal(b, m, deterministic)
}
func (m *PagingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingResult.Merge(m, src)
}
func (m *PagingResult) XXX_Size() int {
	return xxx_messageInfo_PagingResult.Size(m)
}
func (m *PagingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingResult.DiscardUnknown(m)
}

var xxx_messageInfo_PagingResult proto.InternalMessageInfo

func (m *PagingResult) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *PagingResult) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagingResult) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *PagingResult) GetTotalRow() int64 {
	if m != nil {
		return m.TotalRow
	}
	return 0
}

// 狀態
type Status struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

// Server Time
type ServerTimeResp struct {
	ServerTime           string   `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerTimeResp) Reset()         { *m = ServerTimeResp{} }
func (m *ServerTimeResp) String() string { return proto.CompactTextString(m) }
func (*ServerTimeResp) ProtoMessage()    {}
func (*ServerTimeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}
func (m *ServerTimeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTimeResp.Unmarshal(m, b)
}
func (m *ServerTimeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTimeResp.Marshal(b, m, deterministic)
}
func (m *ServerTimeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTimeResp.Merge(m, src)
}
func (m *ServerTimeResp) XXX_Size() int {
	return xxx_messageInfo_ServerTimeResp.Size(m)
}
func (m *ServerTimeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTimeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTimeResp proto.InternalMessageInfo

func (m *ServerTimeResp) GetServerTime() string {
	if m != nil {
		return m.ServerTime
	}
	return ""
}

func init() {
	proto.RegisterEnum("zqbapis.Status_Enum", Status_Enum_name, Status_Enum_value)
	proto.RegisterType((*Paging)(nil), "zqbapis.Paging")
	proto.RegisterType((*PagingResult)(nil), "zqbapis.PagingResult")
	proto.RegisterType((*Status)(nil), "zqbapis.Status")
	proto.RegisterType((*ServerTimeResp)(nil), "zqbapis.ServerTimeResp")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x6a, 0x32, 0x31,
	0x18, 0xc6, 0xbf, 0xf9, 0xb4, 0xa3, 0xbe, 0x4a, 0xb1, 0xa1, 0x85, 0xa1, 0xa5, 0x8c, 0x64, 0x65,
	0x17, 0x55, 0xa4, 0x5d, 0x75, 0x59, 0xe8, 0xa2, 0x3b, 0x89, 0xdd, 0x0f, 0x99, 0xf1, 0x35, 0x0d,
	0x98, 0xc9, 0x38, 0x49, 0x6a, 0xf1, 0x00, 0x3d, 0xa6, 0x87, 0xf0, 0x04, 0x25, 0x19, 0xa8, 0x82,
	0xbb, 0xe7, 0x4f, 0x7e, 0x79, 0x42, 0x60, 0x50, 0x68, 0xa5, 0x74, 0x39, 0xa9, 0x6a, 0x6d, 0x35,
	0xe9, 0xec, 0x36, 0x39, 0xaf, 0xa4, 0xb9, 0x7d, 0x14, 0xd2, 0x7e, 0xba, 0x7c, 0x52, 0x68, 0x35,
	0x15, 0x5a, 0xe8, 0x69, 0xe8, 0x73, 0xb7, 0x0a, 0x2e, 0x98, 0xa0, 0x1a, 0x8e, 0x6e, 0x20, 0x9e,
	0x73, 0x21, 0x4b, 0x41, 0x9e, 0x01, 0x2a, 0x2e, 0x30, 0x93, 0xe5, 0x12, 0xbf, 0x93, 0x68, 0x14,
	0x8d, 0x2f, 0x5e, 0x6f, 0x0e, 0xfb, 0xf4, 0x6a, 0xa5, 0x6b, 0xf5, 0x42, 0x8f, 0x1d, 0x65, 0x3d,
	0x6f, 0xde, 0xbd, 0x26, 0x33, 0x08, 0x26, 0x33, 0x72, 0x87, 0xc9, 0xff, 0x00, 0x5d, 0x1f, 0xf6,
	0xe9, 0xf0, 0x04, 0xf2, 0x15, 0x65, 0x5d, 0xaf, 0x17, 0x5e, 0xfe, 0x44, 0x30, 0x68, 0x36, 0x19,
	0x1a, 0xb7, 0xb6, 0xe4, 0xfe, 0x7c, 0xf9, 0x74, 0xe2, 0xee, 0x6c, 0xe2, 0x78, 0x99, 0x67, 0xad,
	0xb6, 0x7c, 0x9d, 0xf9, 0x24, 0x69, 0x35, 0x6c, 0x48, 0xe6, 0x5c, 0xa0, 0x67, 0x9b, 0xba, 0xd6,
	0xdb, 0xa4, 0x3d, 0x8a, 0xc6, 0x2d, 0xd6, 0x0d, 0x01, 0xd3, 0x5b, 0xfa, 0x00, 0xf1, 0xc2, 0x72,
	0xeb, 0x0c, 0x4d, 0xa1, 0xfd, 0x56, 0x3a, 0x45, 0x00, 0xe2, 0x15, 0x97, 0x6b, 0x5c, 0x0e, 0xff,
	0x91, 0x3e, 0x74, 0x8c, 0x2b, 0x0a, 0x34, 0x66, 0x18, 0xd1, 0x19, 0x5c, 0x2e, 0xb0, 0xfe, 0xc2,
	0xfa, 0x43, 0x2a, 0x64, 0x68, 0x2a, 0x92, 0x42, 0xdf, 0x84, 0x24, 0xb3, 0x52, 0x61, 0x78, 0x75,
	0x8f, 0x81, 0xf9, 0x3b, 0x94, 0xc7, 0xe1, 0x83, 0x9f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdb,
	0x60, 0x92, 0xd5, 0xa8, 0x01, 0x00, 0x00,
}
