// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deposit.proto

package zqbapis

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DepositListReq struct {
	Paging               *Paging  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty" form:"status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositListReq) Reset()         { *m = DepositListReq{} }
func (m *DepositListReq) String() string { return proto.CompactTextString(m) }
func (*DepositListReq) ProtoMessage()    {}
func (*DepositListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{0}
}
func (m *DepositListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositListReq.Unmarshal(m, b)
}
func (m *DepositListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositListReq.Marshal(b, m, deterministic)
}
func (m *DepositListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositListReq.Merge(m, src)
}
func (m *DepositListReq) XXX_Size() int {
	return xxx_messageInfo_DepositListReq.Size(m)
}
func (m *DepositListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositListReq.DiscardUnknown(m)
}

var xxx_messageInfo_DepositListReq proto.InternalMessageInfo

func (m *DepositListReq) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *DepositListReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type DepositListResp struct {
	Paging               *PagingResult  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Data                 []*DepositList `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DepositListResp) Reset()         { *m = DepositListResp{} }
func (m *DepositListResp) String() string { return proto.CompactTextString(m) }
func (*DepositListResp) ProtoMessage()    {}
func (*DepositListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{1}
}
func (m *DepositListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositListResp.Unmarshal(m, b)
}
func (m *DepositListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositListResp.Marshal(b, m, deterministic)
}
func (m *DepositListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositListResp.Merge(m, src)
}
func (m *DepositListResp) XXX_Size() int {
	return xxx_messageInfo_DepositListResp.Size(m)
}
func (m *DepositListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositListResp.DiscardUnknown(m)
}

var xxx_messageInfo_DepositListResp proto.InternalMessageInfo

func (m *DepositListResp) GetPaging() *PagingResult {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *DepositListResp) GetData() []*DepositList {
	if m != nil {
		return m.Data
	}
	return nil
}

type DepositList struct {
	// 充值編號
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 申請時間
	AddedTime string `protobuf:"bytes,2,opt,name=added_time,json=addedTime,proto3" json:"added_time,omitempty"`
	// 變更時間
	UpdateTime string `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// 幣別
	CurrencyCode string `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// 充值金額
	Amount float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// 充值紅利金額
	BonusAmount float64 `protobuf:"fixed64,6,opt,name=bonus_amount,json=bonusAmount,proto3" json:"bonus_amount,omitempty"`
	// 充值紅利%
	BonusRate float64 `protobuf:"fixed64,7,opt,name=bonus_rate,json=bonusRate,proto3" json:"bonus_rate,omitempty"`
	// 充值狀態
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositList) Reset()         { *m = DepositList{} }
func (m *DepositList) String() string { return proto.CompactTextString(m) }
func (*DepositList) ProtoMessage()    {}
func (*DepositList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{2}
}
func (m *DepositList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositList.Unmarshal(m, b)
}
func (m *DepositList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositList.Marshal(b, m, deterministic)
}
func (m *DepositList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositList.Merge(m, src)
}
func (m *DepositList) XXX_Size() int {
	return xxx_messageInfo_DepositList.Size(m)
}
func (m *DepositList) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositList.DiscardUnknown(m)
}

var xxx_messageInfo_DepositList proto.InternalMessageInfo

func (m *DepositList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DepositList) GetAddedTime() string {
	if m != nil {
		return m.AddedTime
	}
	return ""
}

func (m *DepositList) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *DepositList) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *DepositList) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DepositList) GetBonusAmount() float64 {
	if m != nil {
		return m.BonusAmount
	}
	return 0
}

func (m *DepositList) GetBonusRate() float64 {
	if m != nil {
		return m.BonusRate
	}
	return 0
}

func (m *DepositList) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// 轉入方式列表
type DepositMethodResp struct {
	// 轉入方法
	Methods []*DepositMethod `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	// 帳號
	Items                []*DepositMethodItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DepositMethodResp) Reset()         { *m = DepositMethodResp{} }
func (m *DepositMethodResp) String() string { return proto.CompactTextString(m) }
func (*DepositMethodResp) ProtoMessage()    {}
func (*DepositMethodResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{3}
}
func (m *DepositMethodResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositMethodResp.Unmarshal(m, b)
}
func (m *DepositMethodResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositMethodResp.Marshal(b, m, deterministic)
}
func (m *DepositMethodResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositMethodResp.Merge(m, src)
}
func (m *DepositMethodResp) XXX_Size() int {
	return xxx_messageInfo_DepositMethodResp.Size(m)
}
func (m *DepositMethodResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositMethodResp.DiscardUnknown(m)
}

var xxx_messageInfo_DepositMethodResp proto.InternalMessageInfo

func (m *DepositMethodResp) GetMethods() []*DepositMethod {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *DepositMethodResp) GetItems() []*DepositMethodItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type DepositMethod struct {
	// method id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 中文名稱
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 轉入方式
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// 圖片網址
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositMethod) Reset()         { *m = DepositMethod{} }
func (m *DepositMethod) String() string { return proto.CompactTextString(m) }
func (*DepositMethod) ProtoMessage()    {}
func (*DepositMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{4}
}
func (m *DepositMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositMethod.Unmarshal(m, b)
}
func (m *DepositMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositMethod.Marshal(b, m, deterministic)
}
func (m *DepositMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositMethod.Merge(m, src)
}
func (m *DepositMethod) XXX_Size() int {
	return xxx_messageInfo_DepositMethod.Size(m)
}
func (m *DepositMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositMethod.DiscardUnknown(m)
}

var xxx_messageInfo_DepositMethod proto.InternalMessageInfo

func (m *DepositMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DepositMethod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DepositMethod) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DepositMethod) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type DepositMethodItem struct {
	// method id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 帳號
	Accounts             []*DepositAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DepositMethodItem) Reset()         { *m = DepositMethodItem{} }
func (m *DepositMethodItem) String() string { return proto.CompactTextString(m) }
func (*DepositMethodItem) ProtoMessage()    {}
func (*DepositMethodItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{5}
}
func (m *DepositMethodItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositMethodItem.Unmarshal(m, b)
}
func (m *DepositMethodItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositMethodItem.Marshal(b, m, deterministic)
}
func (m *DepositMethodItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositMethodItem.Merge(m, src)
}
func (m *DepositMethodItem) XXX_Size() int {
	return xxx_messageInfo_DepositMethodItem.Size(m)
}
func (m *DepositMethodItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositMethodItem.DiscardUnknown(m)
}

var xxx_messageInfo_DepositMethodItem proto.InternalMessageInfo

func (m *DepositMethodItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DepositMethodItem) GetAccounts() []*DepositAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type DepositAccount struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 銀行名稱
	BankName string `protobuf:"bytes,2,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	// 銀行圖片
	BankImage string `protobuf:"bytes,3,opt,name=bank_image,json=bankImage,proto3" json:"bank_image,omitempty"`
	// 帳戶姓名
	AccountName string `protobuf:"bytes,4,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// 銀行卡號
	AccountNumber string `protobuf:"bytes,5,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// 銀行分支
	AccountBranch string `protobuf:"bytes,6,opt,name=account_branch,json=accountBranch,proto3" json:"account_branch,omitempty"`
	// 最小額度
	Min float64 `protobuf:"fixed64,7,opt,name=min,proto3" json:"min,omitempty"`
	// 最大額度
	Max float64 `protobuf:"fixed64,8,opt,name=max,proto3" json:"max,omitempty"`
	// QRCode圖片
	QrCode               string   `protobuf:"bytes,9,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositAccount) Reset()         { *m = DepositAccount{} }
func (m *DepositAccount) String() string { return proto.CompactTextString(m) }
func (*DepositAccount) ProtoMessage()    {}
func (*DepositAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{6}
}
func (m *DepositAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositAccount.Unmarshal(m, b)
}
func (m *DepositAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositAccount.Marshal(b, m, deterministic)
}
func (m *DepositAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositAccount.Merge(m, src)
}
func (m *DepositAccount) XXX_Size() int {
	return xxx_messageInfo_DepositAccount.Size(m)
}
func (m *DepositAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DepositAccount proto.InternalMessageInfo

func (m *DepositAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DepositAccount) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *DepositAccount) GetBankImage() string {
	if m != nil {
		return m.BankImage
	}
	return ""
}

func (m *DepositAccount) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *DepositAccount) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *DepositAccount) GetAccountBranch() string {
	if m != nil {
		return m.AccountBranch
	}
	return ""
}

func (m *DepositAccount) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *DepositAccount) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *DepositAccount) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

// 轉入
type DepositOrderReq struct {
	// 轉入帳號ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// 轉入金額
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 入款人戶名
	PayName              string   `protobuf:"bytes,3,opt,name=pay_name,json=payName,proto3" json:"pay_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositOrderReq) Reset()         { *m = DepositOrderReq{} }
func (m *DepositOrderReq) String() string { return proto.CompactTextString(m) }
func (*DepositOrderReq) ProtoMessage()    {}
func (*DepositOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{7}
}
func (m *DepositOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositOrderReq.Unmarshal(m, b)
}
func (m *DepositOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositOrderReq.Marshal(b, m, deterministic)
}
func (m *DepositOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositOrderReq.Merge(m, src)
}
func (m *DepositOrderReq) XXX_Size() int {
	return xxx_messageInfo_DepositOrderReq.Size(m)
}
func (m *DepositOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DepositOrderReq proto.InternalMessageInfo

func (m *DepositOrderReq) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DepositOrderReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DepositOrderReq) GetPayName() string {
	if m != nil {
		return m.PayName
	}
	return ""
}

type DepositOrderResp struct {
	// 回傳訊息
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositOrderResp) Reset()         { *m = DepositOrderResp{} }
func (m *DepositOrderResp) String() string { return proto.CompactTextString(m) }
func (*DepositOrderResp) ProtoMessage()    {}
func (*DepositOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d647de60f1ae88, []int{8}
}
func (m *DepositOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositOrderResp.Unmarshal(m, b)
}
func (m *DepositOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositOrderResp.Marshal(b, m, deterministic)
}
func (m *DepositOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositOrderResp.Merge(m, src)
}
func (m *DepositOrderResp) XXX_Size() int {
	return xxx_messageInfo_DepositOrderResp.Size(m)
}
func (m *DepositOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_DepositOrderResp proto.InternalMessageInfo

func (m *DepositOrderResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*DepositListReq)(nil), "zqbapis.DepositListReq")
	proto.RegisterType((*DepositListResp)(nil), "zqbapis.DepositListResp")
	proto.RegisterType((*DepositList)(nil), "zqbapis.DepositList")
	proto.RegisterType((*DepositMethodResp)(nil), "zqbapis.DepositMethodResp")
	proto.RegisterType((*DepositMethod)(nil), "zqbapis.DepositMethod")
	proto.RegisterType((*DepositMethodItem)(nil), "zqbapis.DepositMethodItem")
	proto.RegisterType((*DepositAccount)(nil), "zqbapis.DepositAccount")
	proto.RegisterType((*DepositOrderReq)(nil), "zqbapis.DepositOrderReq")
	proto.RegisterType((*DepositOrderResp)(nil), "zqbapis.DepositOrderResp")
}

func init() { proto.RegisterFile("deposit.proto", fileDescriptor_c2d647de60f1ae88) }

var fileDescriptor_c2d647de60f1ae88 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0x76, 0x6b, 0x9b, 0x93, 0x75, 0x7f, 0x2c, 0xd8, 0xc2, 0xd0, 0xb4, 0x12, 0x84,
	0x28, 0x17, 0xeb, 0xa6, 0xed, 0x8e, 0xbb, 0x0d, 0x6e, 0x26, 0xf1, 0x4f, 0x11, 0x17, 0x48, 0x5c,
	0x54, 0x4e, 0xec, 0x65, 0x06, 0x1c, 0xa7, 0x89, 0x23, 0x56, 0x1e, 0x81, 0x87, 0xe4, 0x21, 0x10,
	0x0f, 0x80, 0x7c, 0xec, 0x84, 0x36, 0xe3, 0xce, 0xfe, 0x9d, 0x2f, 0xfe, 0x7c, 0xbe, 0x9c, 0x04,
	0xc6, 0x8c, 0x17, 0xaa, 0x12, 0x7a, 0x56, 0x94, 0x4a, 0x2b, 0x32, 0xfc, 0xb1, 0x48, 0x68, 0x21,
	0xaa, 0xc3, 0xad, 0x54, 0x49, 0xa9, 0x72, 0x8b, 0x0f, 0x4f, 0x32, 0xa1, 0x6f, 0xeb, 0x64, 0x96,
	0x2a, 0x79, 0x9a, 0xa9, 0x4c, 0x9d, 0x22, 0x4e, 0xea, 0x1b, 0xdc, 0xe1, 0x06, 0x57, 0x56, 0x1e,
	0x31, 0xd8, 0x7e, 0x6d, 0x8f, 0x7d, 0x23, 0x2a, 0x1d, 0xf3, 0x05, 0x79, 0x0e, 0x83, 0x82, 0x66,
	0x22, 0xcf, 0x42, 0x6f, 0xe2, 0x4d, 0x83, 0xf3, 0x9d, 0x99, 0x33, 0x9a, 0x7d, 0x40, 0x1c, 0xbb,
	0x32, 0x79, 0x01, 0x83, 0x4a, 0x53, 0x5d, 0x57, 0x61, 0x6f, 0xe2, 0x4d, 0xfb, 0x57, 0x7b, 0xbf,
	0x7f, 0x1d, 0x8f, 0x6f, 0x54, 0x29, 0x5f, 0x46, 0x96, 0x47, 0xb1, 0x13, 0x44, 0x5f, 0x60, 0x67,
	0xcd, 0xa5, 0x2a, 0xc8, 0x49, 0xc7, 0xe6, 0x61, 0xd7, 0x86, 0x57, 0xf5, 0x37, 0xdd, 0x9a, 0x4d,
	0x61, 0x83, 0x51, 0x4d, 0xc3, 0xde, 0xa4, 0x3f, 0x0d, 0xce, 0x1f, 0xb4, 0xe2, 0xd5, 0x63, 0x51,
	0x11, 0xfd, 0xf1, 0x20, 0x58, 0xa1, 0x64, 0x1b, 0x7a, 0x82, 0xa1, 0x89, 0x1f, 0xf7, 0x04, 0x23,
	0x47, 0x00, 0x94, 0x31, 0xce, 0xe6, 0x5a, 0x48, 0x8e, 0x57, 0xf7, 0x63, 0x1f, 0xc9, 0x47, 0x21,
	0x39, 0x39, 0x86, 0xa0, 0x2e, 0x18, 0xd5, 0xdc, 0xd6, 0xfb, 0x58, 0x07, 0x8b, 0x50, 0xf0, 0x14,
	0xc6, 0x69, 0x5d, 0x96, 0x3c, 0x4f, 0x97, 0xf3, 0x54, 0x31, 0x1e, 0x6e, 0xa0, 0x64, 0xab, 0x81,
	0xaf, 0x14, 0xe3, 0x64, 0x1f, 0x06, 0x54, 0xaa, 0x3a, 0xd7, 0xe1, 0xe6, 0xc4, 0x9b, 0x7a, 0xb1,
	0xdb, 0x91, 0x27, 0xb0, 0x95, 0xa8, 0xbc, 0xae, 0xe6, 0xae, 0x3a, 0xc0, 0x6a, 0x80, 0xec, 0xd2,
	0x4a, 0x8e, 0x00, 0xac, 0xa4, 0xa4, 0x9a, 0x87, 0x43, 0x14, 0xf8, 0x48, 0x62, 0xaa, 0xf1, 0x64,
	0x97, 0xfa, 0x08, 0x7d, 0x9b, 0x88, 0xbf, 0xc3, 0x9e, 0xeb, 0xfa, 0x2d, 0xd7, 0xb7, 0x8a, 0x61,
	0xc8, 0x67, 0x30, 0x94, 0xb8, 0xab, 0x42, 0x0f, 0x83, 0xdb, 0xef, 0x06, 0xe7, 0xc4, 0x8d, 0x8c,
	0x9c, 0xc1, 0xa6, 0xd0, 0x5c, 0x56, 0x2e, 0xe8, 0xc3, 0xff, 0xeb, 0xaf, 0x35, 0x97, 0xb1, 0x15,
	0x46, 0x9f, 0x61, 0xbc, 0x56, 0xbb, 0x17, 0x38, 0x81, 0x8d, 0x9c, 0xb6, 0x51, 0xe3, 0xda, 0x30,
	0xbd, 0x2c, 0x9a, 0x78, 0x71, 0x6d, 0x98, 0x48, 0x55, 0xee, 0xf2, 0xc4, 0x75, 0xf4, 0xa9, 0xd3,
	0x95, 0x31, 0xbe, 0x67, 0x70, 0x01, 0x23, 0x9a, 0xa6, 0x26, 0xbc, 0xe6, 0xda, 0x07, 0xdd, 0x6b,
	0x5f, 0xda, 0x7a, 0xdc, 0x0a, 0xa3, 0x9f, 0xbd, 0x76, 0xf2, 0x5d, 0xf1, 0xde, 0xb9, 0x8f, 0xc1,
	0x4f, 0x68, 0xfe, 0x75, 0xbe, 0x72, 0xfb, 0x91, 0x01, 0xef, 0x4c, 0x07, 0xe6, 0x35, 0x99, 0xa2,
	0x90, 0x34, 0x6b, 0xfa, 0x40, 0xf9, 0xb5, 0x01, 0xe6, 0x45, 0x3b, 0x2b, 0xfb, 0xb8, 0x6d, 0x2a,
	0x70, 0x0c, 0x4f, 0x78, 0x06, 0xdb, 0xad, 0xa4, 0x96, 0x09, 0x2f, 0x71, 0x56, 0xfc, 0x78, 0xdc,
	0x88, 0x10, 0xae, 0xca, 0x92, 0x92, 0xe6, 0xe9, 0x2d, 0x0e, 0xcd, 0x3f, 0xd9, 0x15, 0x42, 0xb2,
	0x0b, 0x7d, 0x29, 0x72, 0x37, 0x2f, 0x66, 0x89, 0x84, 0xde, 0xe1, 0x98, 0x18, 0x42, 0xef, 0xc8,
	0x01, 0x0c, 0x17, 0xa5, 0x1d, 0x5a, 0xdf, 0x0e, 0xcf, 0xa2, 0x34, 0xe3, 0x1a, 0xa5, 0xed, 0xf7,
	0xf9, 0xbe, 0x64, 0xbc, 0x34, 0xbf, 0x01, 0xf3, 0x99, 0x38, 0xdb, 0x36, 0x14, 0xdf, 0x91, 0x6b,
	0xb6, 0x32, 0xe0, 0xbd, 0xb5, 0x01, 0x7f, 0x04, 0xa3, 0x82, 0x2e, 0x6d, 0xcf, 0x36, 0x94, 0x61,
	0x41, 0x97, 0xa6, 0xdf, 0x28, 0x82, 0xdd, 0x75, 0x93, 0xaa, 0xe8, 0x46, 0x9e, 0x0c, 0xf0, 0xaf,
	0x74, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xce, 0xfd, 0xd6, 0xb4, 0xec, 0x04, 0x00, 0x00,
}
