// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: login.proto

package zqbapis

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ScanPayUpdateType int32

const (
	// 首次新增密碼
	ScanPayUpdateType_FirstToAdd ScanPayUpdateType = 0
	// 驗證成功更新密碼
	ScanPayUpdateType_UpdatePwd ScanPayUpdateType = 1
	// 忘記密碼更新
	ScanPayUpdateType_ForgetToUpdate ScanPayUpdateType = 2
)

var ScanPayUpdateType_name = map[int32]string{
	0: "FirstToAdd",
	1: "UpdatePwd",
	2: "ForgetToUpdate",
}

var ScanPayUpdateType_value = map[string]int32{
	"FirstToAdd":     0,
	"UpdatePwd":      1,
	"ForgetToUpdate": 2,
}

func (x ScanPayUpdateType) String() string {
	return proto.EnumName(ScanPayUpdateType_name, int32(x))
}

func (ScanPayUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

type LoginMode_Enum int32

const (
	// 預設，被動與主動皆可
	LoginMode_Default LoginMode_Enum = 0
	// 僅允許被動
	LoginMode_PassiveOnly LoginMode_Enum = 1
	// 僅允許主動
	LoginMode_ActiveOnly LoginMode_Enum = 2
)

var LoginMode_Enum_name = map[int32]string{
	0: "Default",
	1: "PassiveOnly",
	2: "ActiveOnly",
}

var LoginMode_Enum_value = map[string]int32{
	"Default":     0,
	"PassiveOnly": 1,
	"ActiveOnly":  2,
}

func (x LoginMode_Enum) String() string {
	return proto.EnumName(LoginMode_Enum_name, int32(x))
}

func (LoginMode_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0, 0}
}

type LoginIdentifierMode_Enum int32

const (
	// 被動: 會員使用一般驗證登入
	LoginIdentifierMode_Passive LoginIdentifierMode_Enum = 0
	// 主動: 會員使用反轉驗證登入
	LoginIdentifierMode_Active LoginIdentifierMode_Enum = 1
)

var LoginIdentifierMode_Enum_name = map[int32]string{
	0: "Passive",
	1: "Active",
}

var LoginIdentifierMode_Enum_value = map[string]int32{
	"Passive": 0,
	"Active":  1,
}

func (x LoginIdentifierMode_Enum) String() string {
	return proto.EnumName(LoginIdentifierMode_Enum_name, int32(x))
}

func (LoginIdentifierMode_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1, 0}
}

type LoginReverseVerificationStatus_Enum int32

const (
	// 失敗
	LoginReverseVerificationStatus_Failed LoginReverseVerificationStatus_Enum = 0
	// 成功
	LoginReverseVerificationStatus_Success LoginReverseVerificationStatus_Enum = 1
)

var LoginReverseVerificationStatus_Enum_name = map[int32]string{
	0: "Failed",
	1: "Success",
}

var LoginReverseVerificationStatus_Enum_value = map[string]int32{
	"Failed":  0,
	"Success": 1,
}

func (x LoginReverseVerificationStatus_Enum) String() string {
	return proto.EnumName(LoginReverseVerificationStatus_Enum_name, int32(x))
}

func (LoginReverseVerificationStatus_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{9, 0}
}

type LogoutStatus_Enum int32

const (
	LogoutStatus_Failure LogoutStatus_Enum = 0
	LogoutStatus_Success LogoutStatus_Enum = 1
)

var LogoutStatus_Enum_name = map[int32]string{
	0: "Failure",
	1: "Success",
}

var LogoutStatus_Enum_value = map[string]int32{
	"Failure": 0,
	"Success": 1,
}

func (x LogoutStatus_Enum) String() string {
	return proto.EnumName(LogoutStatus_Enum_name, int32(x))
}

func (LogoutStatus_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{13, 0}
}

type RegistrationMode_Enum int32

const (
	// 人工輸入邀請碼
	RegistrationMode_ManualEnterInviteCode RegistrationMode_Enum = 0
	// 自動帶入邀請碼
	RegistrationMode_AutoFillInviteCode RegistrationMode_Enum = 1
)

var RegistrationMode_Enum_name = map[int32]string{
	0: "ManualEnterInviteCode",
	1: "AutoFillInviteCode",
}

var RegistrationMode_Enum_value = map[string]int32{
	"ManualEnterInviteCode": 0,
	"AutoFillInviteCode":    1,
}

func (x RegistrationMode_Enum) String() string {
	return proto.EnumName(RegistrationMode_Enum_name, int32(x))
}

func (RegistrationMode_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{15, 0}
}

// 登入模式
type LoginMode struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMode) Reset()         { *m = LoginMode{} }
func (m *LoginMode) String() string { return proto.CompactTextString(m) }
func (*LoginMode) ProtoMessage()    {}
func (*LoginMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}
func (m *LoginMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMode.Unmarshal(m, b)
}
func (m *LoginMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMode.Marshal(b, m, deterministic)
}
func (m *LoginMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMode.Merge(m, src)
}
func (m *LoginMode) XXX_Size() int {
	return xxx_messageInfo_LoginMode.Size(m)
}
func (m *LoginMode) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMode.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMode proto.InternalMessageInfo

// 驗證模式
type LoginIdentifierMode struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginIdentifierMode) Reset()         { *m = LoginIdentifierMode{} }
func (m *LoginIdentifierMode) String() string { return proto.CompactTextString(m) }
func (*LoginIdentifierMode) ProtoMessage()    {}
func (*LoginIdentifierMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}
func (m *LoginIdentifierMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIdentifierMode.Unmarshal(m, b)
}
func (m *LoginIdentifierMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIdentifierMode.Marshal(b, m, deterministic)
}
func (m *LoginIdentifierMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIdentifierMode.Merge(m, src)
}
func (m *LoginIdentifierMode) XXX_Size() int {
	return xxx_messageInfo_LoginIdentifierMode.Size(m)
}
func (m *LoginIdentifierMode) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIdentifierMode.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIdentifierMode proto.InternalMessageInfo

// 取得登入模式
type LoginModeResp struct {
	Mode                 LoginMode_Enum `protobuf:"varint,1,opt,name=mode,proto3,enum=zqbapis.LoginMode_Enum" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LoginModeResp) Reset()         { *m = LoginModeResp{} }
func (m *LoginModeResp) String() string { return proto.CompactTextString(m) }
func (*LoginModeResp) ProtoMessage()    {}
func (*LoginModeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}
func (m *LoginModeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginModeResp.Unmarshal(m, b)
}
func (m *LoginModeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginModeResp.Marshal(b, m, deterministic)
}
func (m *LoginModeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginModeResp.Merge(m, src)
}
func (m *LoginModeResp) XXX_Size() int {
	return xxx_messageInfo_LoginModeResp.Size(m)
}
func (m *LoginModeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginModeResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginModeResp proto.InternalMessageInfo

func (m *LoginModeResp) GetMode() LoginMode_Enum {
	if m != nil {
		return m.Mode
	}
	return LoginMode_Default
}

// 取得驗證碼
type LoginSendVerificationCodeReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginSendVerificationCodeReq) Reset()         { *m = LoginSendVerificationCodeReq{} }
func (m *LoginSendVerificationCodeReq) String() string { return proto.CompactTextString(m) }
func (*LoginSendVerificationCodeReq) ProtoMessage()    {}
func (*LoginSendVerificationCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}
func (m *LoginSendVerificationCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSendVerificationCodeReq.Unmarshal(m, b)
}
func (m *LoginSendVerificationCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSendVerificationCodeReq.Marshal(b, m, deterministic)
}
func (m *LoginSendVerificationCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSendVerificationCodeReq.Merge(m, src)
}
func (m *LoginSendVerificationCodeReq) XXX_Size() int {
	return xxx_messageInfo_LoginSendVerificationCodeReq.Size(m)
}
func (m *LoginSendVerificationCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSendVerificationCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSendVerificationCodeReq proto.InternalMessageInfo

func (m *LoginSendVerificationCodeReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginSendVerificationCodeReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

type LoginSendVerificationCodeResp struct {
	// 回應訊息
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 可在請求發送時間
	DelayTime int64 `protobuf:"varint,2,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	// 反轉驗證
	ReverseVerify        bool     `protobuf:"varint,3,opt,name=reverse_verify,json=reverseVerify,proto3" json:"reverse_verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginSendVerificationCodeResp) Reset()         { *m = LoginSendVerificationCodeResp{} }
func (m *LoginSendVerificationCodeResp) String() string { return proto.CompactTextString(m) }
func (*LoginSendVerificationCodeResp) ProtoMessage()    {}
func (*LoginSendVerificationCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}
func (m *LoginSendVerificationCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSendVerificationCodeResp.Unmarshal(m, b)
}
func (m *LoginSendVerificationCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSendVerificationCodeResp.Marshal(b, m, deterministic)
}
func (m *LoginSendVerificationCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSendVerificationCodeResp.Merge(m, src)
}
func (m *LoginSendVerificationCodeResp) XXX_Size() int {
	return xxx_messageInfo_LoginSendVerificationCodeResp.Size(m)
}
func (m *LoginSendVerificationCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSendVerificationCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSendVerificationCodeResp proto.InternalMessageInfo

func (m *LoginSendVerificationCodeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginSendVerificationCodeResp) GetDelayTime() int64 {
	if m != nil {
		return m.DelayTime
	}
	return 0
}

func (m *LoginSendVerificationCodeResp) GetReverseVerify() bool {
	if m != nil {
		return m.ReverseVerify
	}
	return false
}

// 取得反轉驗證碼
type LoginSendReverseVerificationCodeReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginSendReverseVerificationCodeReq) Reset()         { *m = LoginSendReverseVerificationCodeReq{} }
func (m *LoginSendReverseVerificationCodeReq) String() string { return proto.CompactTextString(m) }
func (*LoginSendReverseVerificationCodeReq) ProtoMessage()    {}
func (*LoginSendReverseVerificationCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}
func (m *LoginSendReverseVerificationCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSendReverseVerificationCodeReq.Unmarshal(m, b)
}
func (m *LoginSendReverseVerificationCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSendReverseVerificationCodeReq.Marshal(b, m, deterministic)
}
func (m *LoginSendReverseVerificationCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSendReverseVerificationCodeReq.Merge(m, src)
}
func (m *LoginSendReverseVerificationCodeReq) XXX_Size() int {
	return xxx_messageInfo_LoginSendReverseVerificationCodeReq.Size(m)
}
func (m *LoginSendReverseVerificationCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSendReverseVerificationCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSendReverseVerificationCodeReq proto.InternalMessageInfo

func (m *LoginSendReverseVerificationCodeReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginSendReverseVerificationCodeReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

type LoginSendReverseVerificationCodeResp struct {
	// 回應訊息
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 可在請求發送時間
	DelayTime int64 `protobuf:"varint,2,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	// 發送裝置手機號碼
	DeviceMobile         string   `protobuf:"bytes,3,opt,name=device_mobile,json=deviceMobile,proto3" json:"device_mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginSendReverseVerificationCodeResp) Reset()         { *m = LoginSendReverseVerificationCodeResp{} }
func (m *LoginSendReverseVerificationCodeResp) String() string { return proto.CompactTextString(m) }
func (*LoginSendReverseVerificationCodeResp) ProtoMessage()    {}
func (*LoginSendReverseVerificationCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}
func (m *LoginSendReverseVerificationCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSendReverseVerificationCodeResp.Unmarshal(m, b)
}
func (m *LoginSendReverseVerificationCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSendReverseVerificationCodeResp.Marshal(b, m, deterministic)
}
func (m *LoginSendReverseVerificationCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSendReverseVerificationCodeResp.Merge(m, src)
}
func (m *LoginSendReverseVerificationCodeResp) XXX_Size() int {
	return xxx_messageInfo_LoginSendReverseVerificationCodeResp.Size(m)
}
func (m *LoginSendReverseVerificationCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSendReverseVerificationCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSendReverseVerificationCodeResp proto.InternalMessageInfo

func (m *LoginSendReverseVerificationCodeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginSendReverseVerificationCodeResp) GetDelayTime() int64 {
	if m != nil {
		return m.DelayTime
	}
	return 0
}

func (m *LoginSendReverseVerificationCodeResp) GetDeviceMobile() string {
	if m != nil {
		return m.DeviceMobile
	}
	return ""
}

// 反轉驗證
type LoginWaitReverseVerificationReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginWaitReverseVerificationReq) Reset()         { *m = LoginWaitReverseVerificationReq{} }
func (m *LoginWaitReverseVerificationReq) String() string { return proto.CompactTextString(m) }
func (*LoginWaitReverseVerificationReq) ProtoMessage()    {}
func (*LoginWaitReverseVerificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{7}
}
func (m *LoginWaitReverseVerificationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginWaitReverseVerificationReq.Unmarshal(m, b)
}
func (m *LoginWaitReverseVerificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginWaitReverseVerificationReq.Marshal(b, m, deterministic)
}
func (m *LoginWaitReverseVerificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginWaitReverseVerificationReq.Merge(m, src)
}
func (m *LoginWaitReverseVerificationReq) XXX_Size() int {
	return xxx_messageInfo_LoginWaitReverseVerificationReq.Size(m)
}
func (m *LoginWaitReverseVerificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginWaitReverseVerificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginWaitReverseVerificationReq proto.InternalMessageInfo

func (m *LoginWaitReverseVerificationReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginWaitReverseVerificationReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

type LoginWaitReverseVerificationResp struct {
	// 結果狀態
	Status               LoginReverseVerificationStatus_Enum `protobuf:"varint,1,opt,name=status,proto3,enum=zqbapis.LoginReverseVerificationStatus_Enum" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *LoginWaitReverseVerificationResp) Reset()         { *m = LoginWaitReverseVerificationResp{} }
func (m *LoginWaitReverseVerificationResp) String() string { return proto.CompactTextString(m) }
func (*LoginWaitReverseVerificationResp) ProtoMessage()    {}
func (*LoginWaitReverseVerificationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{8}
}
func (m *LoginWaitReverseVerificationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginWaitReverseVerificationResp.Unmarshal(m, b)
}
func (m *LoginWaitReverseVerificationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginWaitReverseVerificationResp.Marshal(b, m, deterministic)
}
func (m *LoginWaitReverseVerificationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginWaitReverseVerificationResp.Merge(m, src)
}
func (m *LoginWaitReverseVerificationResp) XXX_Size() int {
	return xxx_messageInfo_LoginWaitReverseVerificationResp.Size(m)
}
func (m *LoginWaitReverseVerificationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginWaitReverseVerificationResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginWaitReverseVerificationResp proto.InternalMessageInfo

func (m *LoginWaitReverseVerificationResp) GetStatus() LoginReverseVerificationStatus_Enum {
	if m != nil {
		return m.Status
	}
	return LoginReverseVerificationStatus_Failed
}

type LoginReverseVerificationStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReverseVerificationStatus) Reset()         { *m = LoginReverseVerificationStatus{} }
func (m *LoginReverseVerificationStatus) String() string { return proto.CompactTextString(m) }
func (*LoginReverseVerificationStatus) ProtoMessage()    {}
func (*LoginReverseVerificationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{9}
}
func (m *LoginReverseVerificationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReverseVerificationStatus.Unmarshal(m, b)
}
func (m *LoginReverseVerificationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReverseVerificationStatus.Marshal(b, m, deterministic)
}
func (m *LoginReverseVerificationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReverseVerificationStatus.Merge(m, src)
}
func (m *LoginReverseVerificationStatus) XXX_Size() int {
	return xxx_messageInfo_LoginReverseVerificationStatus.Size(m)
}
func (m *LoginReverseVerificationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReverseVerificationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReverseVerificationStatus proto.InternalMessageInfo

// 檢查驗證碼
type LoginIdentifierReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:86)
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// 驗證碼(ex:0857)
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// 模式
	Mode                 LoginIdentifierMode_Enum `protobuf:"varint,4,opt,name=mode,proto3,enum=zqbapis.LoginIdentifierMode_Enum" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *LoginIdentifierReq) Reset()         { *m = LoginIdentifierReq{} }
func (m *LoginIdentifierReq) String() string { return proto.CompactTextString(m) }
func (*LoginIdentifierReq) ProtoMessage()    {}
func (*LoginIdentifierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{10}
}
func (m *LoginIdentifierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIdentifierReq.Unmarshal(m, b)
}
func (m *LoginIdentifierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIdentifierReq.Marshal(b, m, deterministic)
}
func (m *LoginIdentifierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIdentifierReq.Merge(m, src)
}
func (m *LoginIdentifierReq) XXX_Size() int {
	return xxx_messageInfo_LoginIdentifierReq.Size(m)
}
func (m *LoginIdentifierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIdentifierReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIdentifierReq proto.InternalMessageInfo

func (m *LoginIdentifierReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginIdentifierReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *LoginIdentifierReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LoginIdentifierReq) GetMode() LoginIdentifierMode_Enum {
	if m != nil {
		return m.Mode
	}
	return LoginIdentifierMode_Passive
}

type LoginIdentifierResp struct {
	// 證書
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginIdentifierResp) Reset()         { *m = LoginIdentifierResp{} }
func (m *LoginIdentifierResp) String() string { return proto.CompactTextString(m) }
func (*LoginIdentifierResp) ProtoMessage()    {}
func (*LoginIdentifierResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{11}
}
func (m *LoginIdentifierResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIdentifierResp.Unmarshal(m, b)
}
func (m *LoginIdentifierResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIdentifierResp.Marshal(b, m, deterministic)
}
func (m *LoginIdentifierResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIdentifierResp.Merge(m, src)
}
func (m *LoginIdentifierResp) XXX_Size() int {
	return xxx_messageInfo_LoginIdentifierResp.Size(m)
}
func (m *LoginIdentifierResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIdentifierResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIdentifierResp proto.InternalMessageInfo

func (m *LoginIdentifierResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginIdentifierResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginIdentifierResp) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// Logout
type LogoutResp struct {
	Status               LogoutStatus_Enum `protobuf:"varint,1,opt,name=status,proto3,enum=zqbapis.LogoutStatus_Enum" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LogoutResp) Reset()         { *m = LogoutResp{} }
func (m *LogoutResp) String() string { return proto.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()    {}
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{12}
}
func (m *LogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResp.Unmarshal(m, b)
}
func (m *LogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResp.Marshal(b, m, deterministic)
}
func (m *LogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResp.Merge(m, src)
}
func (m *LogoutResp) XXX_Size() int {
	return xxx_messageInfo_LogoutResp.Size(m)
}
func (m *LogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResp proto.InternalMessageInfo

func (m *LogoutResp) GetStatus() LogoutStatus_Enum {
	if m != nil {
		return m.Status
	}
	return LogoutStatus_Failure
}

type LogoutStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutStatus) Reset()         { *m = LogoutStatus{} }
func (m *LogoutStatus) String() string { return proto.CompactTextString(m) }
func (*LogoutStatus) ProtoMessage()    {}
func (*LogoutStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{13}
}
func (m *LogoutStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutStatus.Unmarshal(m, b)
}
func (m *LogoutStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutStatus.Marshal(b, m, deterministic)
}
func (m *LogoutStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutStatus.Merge(m, src)
}
func (m *LogoutStatus) XXX_Size() int {
	return xxx_messageInfo_LogoutStatus.Size(m)
}
func (m *LogoutStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutStatus proto.InternalMessageInfo

// 註冊會員
type LoginRegistrationReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// 密碼
	Passwd string `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	// 再次輸入密碼
	ConfirmPasswd string `protobuf:"bytes,4,opt,name=confirm_passwd,json=confirmPasswd,proto3" json:"confirm_passwd,omitempty"`
	// qq acount
	QqAcount string `protobuf:"bytes,5,opt,name=qq_acount,json=qqAcount,proto3" json:"qq_acount,omitempty"`
	// chinese name
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// 邀請碼
	InviteCode string `protobuf:"bytes,7,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	// 邀請碼錯誤是否忽略
	Mode RegistrationMode_Enum `protobuf:"varint,8,opt,name=mode,proto3,enum=zqbapis.RegistrationMode_Enum" json:"mode,omitempty"`
	// geetest
	Challenge string `protobuf:"bytes,9,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// geetest
	Validate string `protobuf:"bytes,10,opt,name=validate,proto3" json:"validate,omitempty"`
	// geetest
	SecCode              string   `protobuf:"bytes,11,opt,name=sec_code,json=secCode,proto3" json:"sec_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRegistrationReq) Reset()         { *m = LoginRegistrationReq{} }
func (m *LoginRegistrationReq) String() string { return proto.CompactTextString(m) }
func (*LoginRegistrationReq) ProtoMessage()    {}
func (*LoginRegistrationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{14}
}
func (m *LoginRegistrationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRegistrationReq.Unmarshal(m, b)
}
func (m *LoginRegistrationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRegistrationReq.Marshal(b, m, deterministic)
}
func (m *LoginRegistrationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRegistrationReq.Merge(m, src)
}
func (m *LoginRegistrationReq) XXX_Size() int {
	return xxx_messageInfo_LoginRegistrationReq.Size(m)
}
func (m *LoginRegistrationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRegistrationReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRegistrationReq proto.InternalMessageInfo

func (m *LoginRegistrationReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRegistrationReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *LoginRegistrationReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginRegistrationReq) GetConfirmPasswd() string {
	if m != nil {
		return m.ConfirmPasswd
	}
	return ""
}

func (m *LoginRegistrationReq) GetQqAcount() string {
	if m != nil {
		return m.QqAcount
	}
	return ""
}

func (m *LoginRegistrationReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRegistrationReq) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *LoginRegistrationReq) GetMode() RegistrationMode_Enum {
	if m != nil {
		return m.Mode
	}
	return RegistrationMode_ManualEnterInviteCode
}

func (m *LoginRegistrationReq) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *LoginRegistrationReq) GetValidate() string {
	if m != nil {
		return m.Validate
	}
	return ""
}

func (m *LoginRegistrationReq) GetSecCode() string {
	if m != nil {
		return m.SecCode
	}
	return ""
}

type RegistrationMode struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationMode) Reset()         { *m = RegistrationMode{} }
func (m *RegistrationMode) String() string { return proto.CompactTextString(m) }
func (*RegistrationMode) ProtoMessage()    {}
func (*RegistrationMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{15}
}
func (m *RegistrationMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationMode.Unmarshal(m, b)
}
func (m *RegistrationMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationMode.Marshal(b, m, deterministic)
}
func (m *RegistrationMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationMode.Merge(m, src)
}
func (m *RegistrationMode) XXX_Size() int {
	return xxx_messageInfo_RegistrationMode.Size(m)
}
func (m *RegistrationMode) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationMode.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationMode proto.InternalMessageInfo

type LoginRegistrationResp struct {
	// 證書
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRegistrationResp) Reset()         { *m = LoginRegistrationResp{} }
func (m *LoginRegistrationResp) String() string { return proto.CompactTextString(m) }
func (*LoginRegistrationResp) ProtoMessage()    {}
func (*LoginRegistrationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{16}
}
func (m *LoginRegistrationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRegistrationResp.Unmarshal(m, b)
}
func (m *LoginRegistrationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRegistrationResp.Marshal(b, m, deterministic)
}
func (m *LoginRegistrationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRegistrationResp.Merge(m, src)
}
func (m *LoginRegistrationResp) XXX_Size() int {
	return xxx_messageInfo_LoginRegistrationResp.Size(m)
}
func (m *LoginRegistrationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRegistrationResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRegistrationResp proto.InternalMessageInfo

func (m *LoginRegistrationResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRegistrationResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRegistrationResp) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// 以密碼登入
type LoginIdentifierPasswdReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// 密碼
	Passwd string `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	// geetest
	Challenge string `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// geetest
	Validate string `protobuf:"bytes,5,opt,name=validate,proto3" json:"validate,omitempty"`
	// geetest
	SecCode              string   `protobuf:"bytes,6,opt,name=sec_code,json=secCode,proto3" json:"sec_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginIdentifierPasswdReq) Reset()         { *m = LoginIdentifierPasswdReq{} }
func (m *LoginIdentifierPasswdReq) String() string { return proto.CompactTextString(m) }
func (*LoginIdentifierPasswdReq) ProtoMessage()    {}
func (*LoginIdentifierPasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{17}
}
func (m *LoginIdentifierPasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIdentifierPasswdReq.Unmarshal(m, b)
}
func (m *LoginIdentifierPasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIdentifierPasswdReq.Marshal(b, m, deterministic)
}
func (m *LoginIdentifierPasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIdentifierPasswdReq.Merge(m, src)
}
func (m *LoginIdentifierPasswdReq) XXX_Size() int {
	return xxx_messageInfo_LoginIdentifierPasswdReq.Size(m)
}
func (m *LoginIdentifierPasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIdentifierPasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIdentifierPasswdReq proto.InternalMessageInfo

func (m *LoginIdentifierPasswdReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginIdentifierPasswdReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *LoginIdentifierPasswdReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginIdentifierPasswdReq) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *LoginIdentifierPasswdReq) GetValidate() string {
	if m != nil {
		return m.Validate
	}
	return ""
}

func (m *LoginIdentifierPasswdReq) GetSecCode() string {
	if m != nil {
		return m.SecCode
	}
	return ""
}

type LoginIdentifierPasswdResp struct {
	// 證書
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginIdentifierPasswdResp) Reset()         { *m = LoginIdentifierPasswdResp{} }
func (m *LoginIdentifierPasswdResp) String() string { return proto.CompactTextString(m) }
func (*LoginIdentifierPasswdResp) ProtoMessage()    {}
func (*LoginIdentifierPasswdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{18}
}
func (m *LoginIdentifierPasswdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIdentifierPasswdResp.Unmarshal(m, b)
}
func (m *LoginIdentifierPasswdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIdentifierPasswdResp.Marshal(b, m, deterministic)
}
func (m *LoginIdentifierPasswdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIdentifierPasswdResp.Merge(m, src)
}
func (m *LoginIdentifierPasswdResp) XXX_Size() int {
	return xxx_messageInfo_LoginIdentifierPasswdResp.Size(m)
}
func (m *LoginIdentifierPasswdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIdentifierPasswdResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIdentifierPasswdResp proto.InternalMessageInfo

func (m *LoginIdentifierPasswdResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginIdentifierPasswdResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginIdentifierPasswdResp) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// 忘記密碼
type LoginForgetPasswdReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// qq acount
	QqAcount string `protobuf:"bytes,3,opt,name=qq_acount,json=qqAcount,proto3" json:"qq_acount,omitempty"`
	// chinese name
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// geetest
	Challenge string `protobuf:"bytes,5,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// geetest
	Validate string `protobuf:"bytes,6,opt,name=validate,proto3" json:"validate,omitempty"`
	// geetest
	SecCode              string   `protobuf:"bytes,7,opt,name=sec_code,json=secCode,proto3" json:"sec_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginForgetPasswdReq) Reset()         { *m = LoginForgetPasswdReq{} }
func (m *LoginForgetPasswdReq) String() string { return proto.CompactTextString(m) }
func (*LoginForgetPasswdReq) ProtoMessage()    {}
func (*LoginForgetPasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{19}
}
func (m *LoginForgetPasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginForgetPasswdReq.Unmarshal(m, b)
}
func (m *LoginForgetPasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginForgetPasswdReq.Marshal(b, m, deterministic)
}
func (m *LoginForgetPasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginForgetPasswdReq.Merge(m, src)
}
func (m *LoginForgetPasswdReq) XXX_Size() int {
	return xxx_messageInfo_LoginForgetPasswdReq.Size(m)
}
func (m *LoginForgetPasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginForgetPasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginForgetPasswdReq proto.InternalMessageInfo

func (m *LoginForgetPasswdReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginForgetPasswdReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *LoginForgetPasswdReq) GetQqAcount() string {
	if m != nil {
		return m.QqAcount
	}
	return ""
}

func (m *LoginForgetPasswdReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginForgetPasswdReq) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *LoginForgetPasswdReq) GetValidate() string {
	if m != nil {
		return m.Validate
	}
	return ""
}

func (m *LoginForgetPasswdReq) GetSecCode() string {
	if m != nil {
		return m.SecCode
	}
	return ""
}

type LoginForgetPasswdResp struct {
	// 密碼
	Passwd string `protobuf:"bytes,1,opt,name=passwd,proto3" json:"passwd,omitempty"`
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginForgetPasswdResp) Reset()         { *m = LoginForgetPasswdResp{} }
func (m *LoginForgetPasswdResp) String() string { return proto.CompactTextString(m) }
func (*LoginForgetPasswdResp) ProtoMessage()    {}
func (*LoginForgetPasswdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{20}
}
func (m *LoginForgetPasswdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginForgetPasswdResp.Unmarshal(m, b)
}
func (m *LoginForgetPasswdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginForgetPasswdResp.Marshal(b, m, deterministic)
}
func (m *LoginForgetPasswdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginForgetPasswdResp.Merge(m, src)
}
func (m *LoginForgetPasswdResp) XXX_Size() int {
	return xxx_messageInfo_LoginForgetPasswdResp.Size(m)
}
func (m *LoginForgetPasswdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginForgetPasswdResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginForgetPasswdResp proto.InternalMessageInfo

func (m *LoginForgetPasswdResp) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginForgetPasswdResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginForgetPasswdResp) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// 修改密碼
type LoginUpdatePasswdReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// 密碼
	Passwd string `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	// 新密碼
	NewPasswd string `protobuf:"bytes,4,opt,name=new_passwd,json=newPasswd,proto3" json:"new_passwd,omitempty"`
	// 再次輸入新密碼
	ConfirmNewPasswd     string   `protobuf:"bytes,5,opt,name=confirm_new_passwd,json=confirmNewPasswd,proto3" json:"confirm_new_passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUpdatePasswdReq) Reset()         { *m = LoginUpdatePasswdReq{} }
func (m *LoginUpdatePasswdReq) String() string { return proto.CompactTextString(m) }
func (*LoginUpdatePasswdReq) ProtoMessage()    {}
func (*LoginUpdatePasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{21}
}
func (m *LoginUpdatePasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUpdatePasswdReq.Unmarshal(m, b)
}
func (m *LoginUpdatePasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUpdatePasswdReq.Marshal(b, m, deterministic)
}
func (m *LoginUpdatePasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUpdatePasswdReq.Merge(m, src)
}
func (m *LoginUpdatePasswdReq) XXX_Size() int {
	return xxx_messageInfo_LoginUpdatePasswdReq.Size(m)
}
func (m *LoginUpdatePasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUpdatePasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUpdatePasswdReq proto.InternalMessageInfo

func (m *LoginUpdatePasswdReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginUpdatePasswdReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *LoginUpdatePasswdReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginUpdatePasswdReq) GetNewPasswd() string {
	if m != nil {
		return m.NewPasswd
	}
	return ""
}

func (m *LoginUpdatePasswdReq) GetConfirmNewPasswd() string {
	if m != nil {
		return m.ConfirmNewPasswd
	}
	return ""
}

type LoginUpdatePasswdResp struct {
	// 證書
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 國碼(ex:+86)
	CountryCode          string   `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUpdatePasswdResp) Reset()         { *m = LoginUpdatePasswdResp{} }
func (m *LoginUpdatePasswdResp) String() string { return proto.CompactTextString(m) }
func (*LoginUpdatePasswdResp) ProtoMessage()    {}
func (*LoginUpdatePasswdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{22}
}
func (m *LoginUpdatePasswdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUpdatePasswdResp.Unmarshal(m, b)
}
func (m *LoginUpdatePasswdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUpdatePasswdResp.Marshal(b, m, deterministic)
}
func (m *LoginUpdatePasswdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUpdatePasswdResp.Merge(m, src)
}
func (m *LoginUpdatePasswdResp) XXX_Size() int {
	return xxx_messageInfo_LoginUpdatePasswdResp.Size(m)
}
func (m *LoginUpdatePasswdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUpdatePasswdResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUpdatePasswdResp proto.InternalMessageInfo

func (m *LoginUpdatePasswdResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUpdatePasswdResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginUpdatePasswdResp) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// 修改支付密碼
type UpdateScanPayPasswdReq struct {
	//密碼更新方式
	Type ScanPayUpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=zqbapis.ScanPayUpdateType" json:"type,omitempty"`
	// 密碼
	Passwd string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	// 新密碼
	NewPasswd string `protobuf:"bytes,3,opt,name=new_passwd,json=newPasswd,proto3" json:"new_passwd,omitempty"`
	// 再次輸入新密碼
	ConfirmNewPasswd     string   `protobuf:"bytes,4,opt,name=confirm_new_passwd,json=confirmNewPasswd,proto3" json:"confirm_new_passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateScanPayPasswdReq) Reset()         { *m = UpdateScanPayPasswdReq{} }
func (m *UpdateScanPayPasswdReq) String() string { return proto.CompactTextString(m) }
func (*UpdateScanPayPasswdReq) ProtoMessage()    {}
func (*UpdateScanPayPasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{23}
}
func (m *UpdateScanPayPasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScanPayPasswdReq.Unmarshal(m, b)
}
func (m *UpdateScanPayPasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScanPayPasswdReq.Marshal(b, m, deterministic)
}
func (m *UpdateScanPayPasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScanPayPasswdReq.Merge(m, src)
}
func (m *UpdateScanPayPasswdReq) XXX_Size() int {
	return xxx_messageInfo_UpdateScanPayPasswdReq.Size(m)
}
func (m *UpdateScanPayPasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScanPayPasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScanPayPasswdReq proto.InternalMessageInfo

func (m *UpdateScanPayPasswdReq) GetType() ScanPayUpdateType {
	if m != nil {
		return m.Type
	}
	return ScanPayUpdateType_FirstToAdd
}

func (m *UpdateScanPayPasswdReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *UpdateScanPayPasswdReq) GetNewPasswd() string {
	if m != nil {
		return m.NewPasswd
	}
	return ""
}

func (m *UpdateScanPayPasswdReq) GetConfirmNewPasswd() string {
	if m != nil {
		return m.ConfirmNewPasswd
	}
	return ""
}

//修改支付密碼回應
type UpdateScanPayPasswdResp struct {
	// 狀態 0=失敗 1=成功
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateScanPayPasswdResp) Reset()         { *m = UpdateScanPayPasswdResp{} }
func (m *UpdateScanPayPasswdResp) String() string { return proto.CompactTextString(m) }
func (*UpdateScanPayPasswdResp) ProtoMessage()    {}
func (*UpdateScanPayPasswdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{24}
}
func (m *UpdateScanPayPasswdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScanPayPasswdResp.Unmarshal(m, b)
}
func (m *UpdateScanPayPasswdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScanPayPasswdResp.Marshal(b, m, deterministic)
}
func (m *UpdateScanPayPasswdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScanPayPasswdResp.Merge(m, src)
}
func (m *UpdateScanPayPasswdResp) XXX_Size() int {
	return xxx_messageInfo_UpdateScanPayPasswdResp.Size(m)
}
func (m *UpdateScanPayPasswdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScanPayPasswdResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScanPayPasswdResp proto.InternalMessageInfo

func (m *UpdateScanPayPasswdResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 忘記支付密碼
type ScanPayForgetPasswdReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// qq account
	QqAccount string `protobuf:"bytes,2,opt,name=qq_account,json=qqAccount,proto3" json:"qq_account,omitempty"`
	// chinese name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 登入密碼
	LoginPasswd          string   `protobuf:"bytes,4,opt,name=login_passwd,json=loginPasswd,proto3" json:"login_passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayForgetPasswdReq) Reset()         { *m = ScanPayForgetPasswdReq{} }
func (m *ScanPayForgetPasswdReq) String() string { return proto.CompactTextString(m) }
func (*ScanPayForgetPasswdReq) ProtoMessage()    {}
func (*ScanPayForgetPasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{25}
}
func (m *ScanPayForgetPasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayForgetPasswdReq.Unmarshal(m, b)
}
func (m *ScanPayForgetPasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayForgetPasswdReq.Marshal(b, m, deterministic)
}
func (m *ScanPayForgetPasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayForgetPasswdReq.Merge(m, src)
}
func (m *ScanPayForgetPasswdReq) XXX_Size() int {
	return xxx_messageInfo_ScanPayForgetPasswdReq.Size(m)
}
func (m *ScanPayForgetPasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayForgetPasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayForgetPasswdReq proto.InternalMessageInfo

func (m *ScanPayForgetPasswdReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ScanPayForgetPasswdReq) GetQqAccount() string {
	if m != nil {
		return m.QqAccount
	}
	return ""
}

func (m *ScanPayForgetPasswdReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanPayForgetPasswdReq) GetLoginPasswd() string {
	if m != nil {
		return m.LoginPasswd
	}
	return ""
}

// 忘記支付密碼驗證結果
type ScanPayForgetPasswdResp struct {
	// 狀態 0=失敗 1=成功
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayForgetPasswdResp) Reset()         { *m = ScanPayForgetPasswdResp{} }
func (m *ScanPayForgetPasswdResp) String() string { return proto.CompactTextString(m) }
func (*ScanPayForgetPasswdResp) ProtoMessage()    {}
func (*ScanPayForgetPasswdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{26}
}
func (m *ScanPayForgetPasswdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayForgetPasswdResp.Unmarshal(m, b)
}
func (m *ScanPayForgetPasswdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayForgetPasswdResp.Marshal(b, m, deterministic)
}
func (m *ScanPayForgetPasswdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayForgetPasswdResp.Merge(m, src)
}
func (m *ScanPayForgetPasswdResp) XXX_Size() int {
	return xxx_messageInfo_ScanPayForgetPasswdResp.Size(m)
}
func (m *ScanPayForgetPasswdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayForgetPasswdResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayForgetPasswdResp proto.InternalMessageInfo

func (m *ScanPayForgetPasswdResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 是否首次使用
type ScanPayFirstUseResp struct {
	// 狀態 0=非首次 1=首次
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayFirstUseResp) Reset()         { *m = ScanPayFirstUseResp{} }
func (m *ScanPayFirstUseResp) String() string { return proto.CompactTextString(m) }
func (*ScanPayFirstUseResp) ProtoMessage()    {}
func (*ScanPayFirstUseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{27}
}
func (m *ScanPayFirstUseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayFirstUseResp.Unmarshal(m, b)
}
func (m *ScanPayFirstUseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayFirstUseResp.Marshal(b, m, deterministic)
}
func (m *ScanPayFirstUseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayFirstUseResp.Merge(m, src)
}
func (m *ScanPayFirstUseResp) XXX_Size() int {
	return xxx_messageInfo_ScanPayFirstUseResp.Size(m)
}
func (m *ScanPayFirstUseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayFirstUseResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayFirstUseResp proto.InternalMessageInfo

func (m *ScanPayFirstUseResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//檢查支付密碼是否正確
type CheckScanPayPasswdReq struct {
	// 支付密碼
	Passwd               string   `protobuf:"bytes,1,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckScanPayPasswdReq) Reset()         { *m = CheckScanPayPasswdReq{} }
func (m *CheckScanPayPasswdReq) String() string { return proto.CompactTextString(m) }
func (*CheckScanPayPasswdReq) ProtoMessage()    {}
func (*CheckScanPayPasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{28}
}
func (m *CheckScanPayPasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckScanPayPasswdReq.Unmarshal(m, b)
}
func (m *CheckScanPayPasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckScanPayPasswdReq.Marshal(b, m, deterministic)
}
func (m *CheckScanPayPasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckScanPayPasswdReq.Merge(m, src)
}
func (m *CheckScanPayPasswdReq) XXX_Size() int {
	return xxx_messageInfo_CheckScanPayPasswdReq.Size(m)
}
func (m *CheckScanPayPasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckScanPayPasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckScanPayPasswdReq proto.InternalMessageInfo

func (m *CheckScanPayPasswdReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type CheckScanPayPasswdResp struct {
	// 0=驗證錯誤 1=驗證正確
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckScanPayPasswdResp) Reset()         { *m = CheckScanPayPasswdResp{} }
func (m *CheckScanPayPasswdResp) String() string { return proto.CompactTextString(m) }
func (*CheckScanPayPasswdResp) ProtoMessage()    {}
func (*CheckScanPayPasswdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{29}
}
func (m *CheckScanPayPasswdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckScanPayPasswdResp.Unmarshal(m, b)
}
func (m *CheckScanPayPasswdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckScanPayPasswdResp.Marshal(b, m, deterministic)
}
func (m *CheckScanPayPasswdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckScanPayPasswdResp.Merge(m, src)
}
func (m *CheckScanPayPasswdResp) XXX_Size() int {
	return xxx_messageInfo_CheckScanPayPasswdResp.Size(m)
}
func (m *CheckScanPayPasswdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckScanPayPasswdResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckScanPayPasswdResp proto.InternalMessageInfo

func (m *CheckScanPayPasswdResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterEnum("zqbapis.ScanPayUpdateType", ScanPayUpdateType_name, ScanPayUpdateType_value)
	proto.RegisterEnum("zqbapis.LoginMode_Enum", LoginMode_Enum_name, LoginMode_Enum_value)
	proto.RegisterEnum("zqbapis.LoginIdentifierMode_Enum", LoginIdentifierMode_Enum_name, LoginIdentifierMode_Enum_value)
	proto.RegisterEnum("zqbapis.LoginReverseVerificationStatus_Enum", LoginReverseVerificationStatus_Enum_name, LoginReverseVerificationStatus_Enum_value)
	proto.RegisterEnum("zqbapis.LogoutStatus_Enum", LogoutStatus_Enum_name, LogoutStatus_Enum_value)
	proto.RegisterEnum("zqbapis.RegistrationMode_Enum", RegistrationMode_Enum_name, RegistrationMode_Enum_value)
	proto.RegisterType((*LoginMode)(nil), "zqbapis.LoginMode")
	proto.RegisterType((*LoginIdentifierMode)(nil), "zqbapis.LoginIdentifierMode")
	proto.RegisterType((*LoginModeResp)(nil), "zqbapis.LoginModeResp")
	proto.RegisterType((*LoginSendVerificationCodeReq)(nil), "zqbapis.LoginSendVerificationCodeReq")
	proto.RegisterType((*LoginSendVerificationCodeResp)(nil), "zqbapis.LoginSendVerificationCodeResp")
	proto.RegisterType((*LoginSendReverseVerificationCodeReq)(nil), "zqbapis.LoginSendReverseVerificationCodeReq")
	proto.RegisterType((*LoginSendReverseVerificationCodeResp)(nil), "zqbapis.LoginSendReverseVerificationCodeResp")
	proto.RegisterType((*LoginWaitReverseVerificationReq)(nil), "zqbapis.LoginWaitReverseVerificationReq")
	proto.RegisterType((*LoginWaitReverseVerificationResp)(nil), "zqbapis.LoginWaitReverseVerificationResp")
	proto.RegisterType((*LoginReverseVerificationStatus)(nil), "zqbapis.LoginReverseVerificationStatus")
	proto.RegisterType((*LoginIdentifierReq)(nil), "zqbapis.LoginIdentifierReq")
	proto.RegisterType((*LoginIdentifierResp)(nil), "zqbapis.LoginIdentifierResp")
	proto.RegisterType((*LogoutResp)(nil), "zqbapis.LogoutResp")
	proto.RegisterType((*LogoutStatus)(nil), "zqbapis.LogoutStatus")
	proto.RegisterType((*LoginRegistrationReq)(nil), "zqbapis.LoginRegistrationReq")
	proto.RegisterType((*RegistrationMode)(nil), "zqbapis.RegistrationMode")
	proto.RegisterType((*LoginRegistrationResp)(nil), "zqbapis.LoginRegistrationResp")
	proto.RegisterType((*LoginIdentifierPasswdReq)(nil), "zqbapis.LoginIdentifierPasswdReq")
	proto.RegisterType((*LoginIdentifierPasswdResp)(nil), "zqbapis.LoginIdentifierPasswdResp")
	proto.RegisterType((*LoginForgetPasswdReq)(nil), "zqbapis.LoginForgetPasswdReq")
	proto.RegisterType((*LoginForgetPasswdResp)(nil), "zqbapis.LoginForgetPasswdResp")
	proto.RegisterType((*LoginUpdatePasswdReq)(nil), "zqbapis.LoginUpdatePasswdReq")
	proto.RegisterType((*LoginUpdatePasswdResp)(nil), "zqbapis.LoginUpdatePasswdResp")
	proto.RegisterType((*UpdateScanPayPasswdReq)(nil), "zqbapis.UpdateScanPayPasswdReq")
	proto.RegisterType((*UpdateScanPayPasswdResp)(nil), "zqbapis.UpdateScanPayPasswdResp")
	proto.RegisterType((*ScanPayForgetPasswdReq)(nil), "zqbapis.ScanPayForgetPasswdReq")
	proto.RegisterType((*ScanPayForgetPasswdResp)(nil), "zqbapis.ScanPayForgetPasswdResp")
	proto.RegisterType((*ScanPayFirstUseResp)(nil), "zqbapis.ScanPayFirstUseResp")
	proto.RegisterType((*CheckScanPayPasswdReq)(nil), "zqbapis.CheckScanPayPasswdReq")
	proto.RegisterType((*CheckScanPayPasswdResp)(nil), "zqbapis.CheckScanPayPasswdResp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x75, 0xe6, 0xc8, 0xf2, 0xcf, 0x7f, 0x13, 0x2b, 0x72, 0x1a, 0xc7, 0x36, 0xd3, 0x02,
	0x41, 0x9b, 0xaa, 0xa9, 0x7b, 0x00, 0x0a, 0xf4, 0xa2, 0x42, 0x12, 0x03, 0x01, 0xe2, 0xd6, 0x90,
	0x9d, 0x16, 0x05, 0x0a, 0xa8, 0x6b, 0x72, 0x24, 0x6f, 0x43, 0x91, 0x14, 0x77, 0x29, 0x43, 0xbd,
	0xe9, 0x4d, 0xd1, 0x87, 0xe8, 0x3b, 0xf4, 0xb6, 0x0f, 0xd0, 0x97, 0xe8, 0x43, 0xf4, 0x25, 0x0a,
	0xee, 0xae, 0x24, 0x52, 0x07, 0x36, 0x80, 0xad, 0x3b, 0xed, 0xec, 0xcc, 0xec, 0x37, 0xdf, 0xcc,
	0xb7, 0xd4, 0x42, 0xdd, 0x0b, 0x06, 0xcc, 0x6f, 0x87, 0x51, 0x20, 0x02, 0x52, 0xfd, 0x79, 0x74,
	0x49, 0x43, 0xc6, 0xed, 0x0e, 0x98, 0xaf, 0x12, 0xfb, 0x69, 0xe0, 0xa2, 0xfd, 0x29, 0x94, 0x5e,
	0xf8, 0xf1, 0x90, 0xd4, 0xa1, 0xfa, 0x1c, 0xfb, 0x34, 0xf6, 0x84, 0xb5, 0x45, 0xfe, 0x07, 0xf5,
	0x33, 0xca, 0x39, 0x1b, 0xe3, 0x37, 0xbe, 0x37, 0xb1, 0x0c, 0xb2, 0x03, 0xd0, 0x71, 0xc4, 0x74,
	0x5d, 0xb0, 0x3f, 0x87, 0x3b, 0x32, 0xc5, 0x4b, 0x17, 0x7d, 0xc1, 0xfa, 0x0c, 0x23, 0x99, 0xec,
	0x60, 0x9e, 0x4c, 0xc7, 0x5b, 0x5b, 0x04, 0xa0, 0xa2, 0x62, 0x2d, 0xc3, 0xfe, 0x12, 0x1a, 0xb3,
	0xa3, 0xbb, 0xc8, 0x43, 0xf2, 0x01, 0x94, 0x86, 0x81, 0x8b, 0x2d, 0xe3, 0xd0, 0x78, 0xbc, 0x73,
	0x7c, 0xaf, 0xad, 0x31, 0xb6, 0x67, 0x5e, 0xed, 0x24, 0x61, 0x57, 0x3a, 0xd9, 0xdf, 0xc3, 0x03,
	0x69, 0x3f, 0x47, 0xdf, 0xfd, 0x16, 0x23, 0xd6, 0x67, 0x0e, 0x15, 0x2c, 0xf0, 0x9f, 0xc9, 0x6c,
	0x23, 0xd2, 0x84, 0xca, 0x30, 0xb8, 0x64, 0x9e, 0x4a, 0x67, 0x76, 0xf5, 0x8a, 0x1c, 0xc1, 0xb6,
	0x13, 0xc4, 0xbe, 0x88, 0x26, 0x3d, 0x27, 0x39, 0xac, 0x20, 0x77, 0xeb, 0xda, 0x96, 0x44, 0xdb,
	0xbf, 0xc0, 0x7e, 0x4e, 0x6a, 0x1e, 0x92, 0x16, 0x54, 0x87, 0xc8, 0x39, 0x1d, 0x4c, 0x93, 0x4f,
	0x97, 0x64, 0x1f, 0xc0, 0x45, 0x8f, 0x4e, 0x7a, 0x82, 0x0d, 0x55, 0xee, 0x62, 0xd7, 0x94, 0x96,
	0x0b, 0x36, 0x44, 0xf2, 0x1e, 0xec, 0x44, 0x38, 0xc6, 0x88, 0x63, 0x6f, 0x9c, 0x24, 0x9e, 0xb4,
	0x8a, 0x87, 0xc6, 0xe3, 0x5a, 0xb7, 0xa1, 0xad, 0xf2, 0xb4, 0x89, 0xfd, 0x23, 0x3c, 0x9a, 0x01,
	0xe8, 0xa6, 0x76, 0x6e, 0xaf, 0xc4, 0x5f, 0x0d, 0x78, 0xf7, 0xbf, 0x8f, 0xb8, 0x49, 0xa9, 0x8f,
	0xa0, 0xe1, 0xe2, 0x98, 0x39, 0xd8, 0xd3, 0x18, 0x8b, 0x32, 0x7c, 0x5b, 0x19, 0x4f, 0xa5, 0xcd,
	0xfe, 0x01, 0x0e, 0x24, 0x8a, 0xef, 0x28, 0x13, 0x2b, 0x50, 0xdc, 0xb0, 0xc8, 0x2b, 0x38, 0xcc,
	0xcf, 0xce, 0x43, 0xf2, 0x1c, 0x2a, 0x5c, 0x50, 0x11, 0x73, 0x3d, 0x75, 0x4f, 0xb2, 0x53, 0xb7,
	0x22, 0xec, 0x5c, 0xba, 0xab, 0x51, 0xd4, 0xb1, 0x76, 0x07, 0x1e, 0xe6, 0xbb, 0xcf, 0xd4, 0x00,
	0x50, 0x39, 0xa1, 0xcc, 0x43, 0xd7, 0xda, 0x4a, 0x94, 0x71, 0x1e, 0x3b, 0x0e, 0x72, 0x6e, 0x19,
	0xf6, 0xef, 0x06, 0x90, 0x05, 0x19, 0xdd, 0xac, 0x7c, 0x42, 0xa0, 0x24, 0xb7, 0x14, 0xf1, 0xf2,
	0x37, 0xf9, 0x4c, 0x4b, 0xac, 0x24, 0x8b, 0x3d, 0xca, 0x16, 0x9b, 0x15, 0x70, 0x5a, 0x6c, 0xfd,
	0x25, 0x89, 0x4b, 0xf2, 0xee, 0x42, 0x59, 0x04, 0x6f, 0xd0, 0xd7, 0xd8, 0xd4, 0x22, 0x05, 0xb9,
	0x90, 0x0b, 0xb9, 0xb8, 0xdc, 0xb1, 0xaf, 0x00, 0x5e, 0x05, 0x83, 0x20, 0x16, 0x32, 0xfd, 0xf1,
	0x42, 0x6f, 0xee, 0xa7, 0xe1, 0x06, 0xb1, 0x58, 0xd5, 0x89, 0xa7, 0xb0, 0x9d, 0xde, 0xb4, 0x0f,
	0xe7, 0xb7, 0x50, 0xc2, 0x7b, 0x1c, 0xe1, 0x22, 0xf1, 0xff, 0x14, 0xe0, 0xae, 0x6e, 0xde, 0x80,
	0x71, 0x11, 0xdd, 0xc2, 0xe4, 0x25, 0xa1, 0x21, 0xe5, 0xfc, 0xda, 0xd5, 0x45, 0xea, 0x55, 0xa2,
	0x7f, 0x27, 0xf0, 0xfb, 0x2c, 0x1a, 0xf6, 0xf4, 0x7e, 0x49, 0xee, 0x37, 0xb4, 0xf5, 0x4c, 0xb9,
	0xbd, 0x03, 0xe6, 0x68, 0xd4, 0xa3, 0x32, 0x63, 0xab, 0x2c, 0x3d, 0x6a, 0xa3, 0x51, 0x47, 0xae,
	0x93, 0xb6, 0xfa, 0x74, 0x88, 0xad, 0x8a, 0x6a, 0x6b, 0xf2, 0x9b, 0x1c, 0x40, 0x9d, 0xf9, 0x63,
	0x26, 0x50, 0x21, 0xaa, 0xca, 0x2d, 0x50, 0x26, 0x09, 0xe8, 0x58, 0xf7, 0xbd, 0x26, 0x89, 0x7c,
	0x38, 0x23, 0x32, 0x5d, 0xf3, 0x42, 0xd3, 0xc9, 0x03, 0x30, 0x9d, 0x2b, 0xea, 0x79, 0xe8, 0x0f,
	0xb0, 0x65, 0xca, 0x94, 0x73, 0x03, 0xb9, 0x0f, 0xb5, 0x31, 0xf5, 0x98, 0x4b, 0x05, 0xb6, 0x40,
	0x41, 0x9c, 0xae, 0xc9, 0x1e, 0xd4, 0x38, 0x3a, 0x0a, 0x4b, 0x5d, 0xdd, 0x1a, 0x1c, 0x1d, 0xd9,
	0xe1, 0x53, 0xb0, 0x16, 0xcf, 0xb4, 0xbf, 0xd0, 0x3d, 0xda, 0x83, 0xdd, 0x53, 0xea, 0xc7, 0xd4,
	0x7b, 0xe1, 0x0b, 0x8c, 0x5e, 0xce, 0xd0, 0x5b, 0x5b, 0xa4, 0x09, 0xa4, 0x13, 0x8b, 0xe0, 0x84,
	0x79, 0x5e, 0xca, 0x6e, 0xd8, 0x57, 0xb0, 0xbb, 0xa2, 0x77, 0x9b, 0x18, 0xcd, 0xbf, 0x0c, 0x68,
	0x2d, 0x68, 0x40, 0x75, 0x6b, 0x43, 0xa3, 0x92, 0x61, 0xbf, 0x94, 0xc7, 0x7e, 0x39, 0x87, 0xfd,
	0x4a, 0x96, 0x7d, 0x0f, 0xf6, 0xd6, 0xd4, 0xb0, 0x09, 0xca, 0xfe, 0x36, 0xb4, 0xb2, 0x4e, 0x82,
	0x68, 0x80, 0xe2, 0x56, 0xe8, 0xca, 0x48, 0xa3, 0xb8, 0x46, 0x1a, 0xa5, 0x94, 0x34, 0x32, 0x3c,
	0x96, 0xf3, 0x78, 0xac, 0xe4, 0xf0, 0x58, 0xcd, 0xf2, 0xf8, 0x93, 0x1e, 0xbb, 0x6c, 0x61, 0x3c,
	0x4c, 0x75, 0xd3, 0xc8, 0x74, 0xf3, 0x06, 0x2c, 0xfe, 0x39, 0x65, 0xf1, 0x75, 0x98, 0xc0, 0xda,
	0xe8, 0xd0, 0xed, 0x03, 0xf8, 0x78, 0x9d, 0xbd, 0x9b, 0x4c, 0x1f, 0xaf, 0xf5, 0xbd, 0xf4, 0x04,
	0xc8, 0xf4, 0xfa, 0x4a, 0xb9, 0x29, 0x52, 0x2d, 0xbd, 0xf3, 0xf5, 0xd4, 0x7b, 0xa6, 0xcd, 0x2c,
	0xee, 0x4d, 0x0c, 0xda, 0x1f, 0x06, 0x34, 0xd5, 0x29, 0xe7, 0x0e, 0xf5, 0xcf, 0xe8, 0x64, 0x4e,
	0x52, 0x1b, 0x4a, 0x62, 0x12, 0xe2, 0xd2, 0x17, 0x44, 0x3b, 0xaa, 0xa8, 0x8b, 0x49, 0x88, 0x5d,
	0xe9, 0x97, 0x62, 0xa6, 0x90, 0xc3, 0x4c, 0xf1, 0xed, 0x98, 0x29, 0xad, 0x61, 0xe6, 0x63, 0xb8,
	0xb7, 0x12, 0xae, 0x1a, 0xa0, 0xd4, 0x37, 0xaf, 0x3c, 0xfb, 0xae, 0xfd, 0x66, 0x40, 0x53, 0x7b,
	0xbf, 0xad, 0x9a, 0xf6, 0x01, 0xa4, 0x54, 0x94, 0x56, 0x54, 0x39, 0x66, 0xa2, 0x95, 0xac, 0x58,
	0x8a, 0x29, 0xb1, 0x1c, 0xc1, 0xb6, 0x7c, 0x25, 0x64, 0x0b, 0x50, 0x2f, 0x87, 0x39, 0xf6, 0x95,
	0x38, 0x72, 0xb0, 0x7f, 0x08, 0x77, 0xa6, 0x21, 0x2c, 0xe2, 0xe2, 0x35, 0xc7, 0x5c, 0xf7, 0x8f,
	0x60, 0xf7, 0xd9, 0x15, 0x3a, 0x6f, 0x96, 0x7a, 0xb9, 0x46, 0x5c, 0xf6, 0x53, 0x68, 0xae, 0x0a,
	0x58, 0x7f, 0xc4, 0xfb, 0x27, 0xf0, 0xff, 0xa5, 0x01, 0x48, 0xde, 0x35, 0x12, 0xdf, 0x45, 0xd0,
	0x71, 0x93, 0xbf, 0x67, 0x0d, 0x30, 0xf5, 0xe8, 0x5e, 0xbb, 0x96, 0x41, 0x08, 0xec, 0xa8, 0x8a,
	0x2f, 0x02, 0x65, 0xb6, 0x0a, 0x97, 0x15, 0xf9, 0x9a, 0xfa, 0xe4, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x70, 0x7c, 0x99, 0x39, 0x5c, 0x0d, 0x00, 0x00,
}
