// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scanpay.proto

package zqbapis

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ScanPayScanReq struct {
	// qrcode
	QrCode               string   `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayScanReq) Reset()         { *m = ScanPayScanReq{} }
func (m *ScanPayScanReq) String() string { return proto.CompactTextString(m) }
func (*ScanPayScanReq) ProtoMessage()    {}
func (*ScanPayScanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e620eaf8bd5845ef, []int{0}
}
func (m *ScanPayScanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayScanReq.Unmarshal(m, b)
}
func (m *ScanPayScanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayScanReq.Marshal(b, m, deterministic)
}
func (m *ScanPayScanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayScanReq.Merge(m, src)
}
func (m *ScanPayScanReq) XXX_Size() int {
	return xxx_messageInfo_ScanPayScanReq.Size(m)
}
func (m *ScanPayScanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayScanReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayScanReq proto.InternalMessageInfo

func (m *ScanPayScanReq) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

type ScanPayScanResp struct {
	// 回傳RecordId
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 支付金額
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	//過期時間
	ExpiredTime          string   `protobuf:"bytes,3,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayScanResp) Reset()         { *m = ScanPayScanResp{} }
func (m *ScanPayScanResp) String() string { return proto.CompactTextString(m) }
func (*ScanPayScanResp) ProtoMessage()    {}
func (*ScanPayScanResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e620eaf8bd5845ef, []int{1}
}
func (m *ScanPayScanResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayScanResp.Unmarshal(m, b)
}
func (m *ScanPayScanResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayScanResp.Marshal(b, m, deterministic)
}
func (m *ScanPayScanResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayScanResp.Merge(m, src)
}
func (m *ScanPayScanResp) XXX_Size() int {
	return xxx_messageInfo_ScanPayScanResp.Size(m)
}
func (m *ScanPayScanResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayScanResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayScanResp proto.InternalMessageInfo

func (m *ScanPayScanResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ScanPayScanResp) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ScanPayScanResp) GetExpiredTime() string {
	if m != nil {
		return m.ExpiredTime
	}
	return ""
}

type ScanPayAddPayReq struct {
	// APP回傳RecordId
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 支付金額
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 支付密碼
	Passwd               string   `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayAddPayReq) Reset()         { *m = ScanPayAddPayReq{} }
func (m *ScanPayAddPayReq) String() string { return proto.CompactTextString(m) }
func (*ScanPayAddPayReq) ProtoMessage()    {}
func (*ScanPayAddPayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e620eaf8bd5845ef, []int{2}
}
func (m *ScanPayAddPayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayAddPayReq.Unmarshal(m, b)
}
func (m *ScanPayAddPayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayAddPayReq.Marshal(b, m, deterministic)
}
func (m *ScanPayAddPayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayAddPayReq.Merge(m, src)
}
func (m *ScanPayAddPayReq) XXX_Size() int {
	return xxx_messageInfo_ScanPayAddPayReq.Size(m)
}
func (m *ScanPayAddPayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayAddPayReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayAddPayReq proto.InternalMessageInfo

func (m *ScanPayAddPayReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ScanPayAddPayReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ScanPayAddPayReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type ScanPayAddPayResp struct {
	// 交易結果 0=失敗 1=成功
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 支付金額
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 註記
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanPayAddPayResp) Reset()         { *m = ScanPayAddPayResp{} }
func (m *ScanPayAddPayResp) String() string { return proto.CompactTextString(m) }
func (*ScanPayAddPayResp) ProtoMessage()    {}
func (*ScanPayAddPayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e620eaf8bd5845ef, []int{3}
}
func (m *ScanPayAddPayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanPayAddPayResp.Unmarshal(m, b)
}
func (m *ScanPayAddPayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanPayAddPayResp.Marshal(b, m, deterministic)
}
func (m *ScanPayAddPayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanPayAddPayResp.Merge(m, src)
}
func (m *ScanPayAddPayResp) XXX_Size() int {
	return xxx_messageInfo_ScanPayAddPayResp.Size(m)
}
func (m *ScanPayAddPayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanPayAddPayResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanPayAddPayResp proto.InternalMessageInfo

func (m *ScanPayAddPayResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ScanPayAddPayResp) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ScanPayAddPayResp) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func init() {
	proto.RegisterType((*ScanPayScanReq)(nil), "zqbapis.ScanPayScanReq")
	proto.RegisterType((*ScanPayScanResp)(nil), "zqbapis.ScanPayScanResp")
	proto.RegisterType((*ScanPayAddPayReq)(nil), "zqbapis.ScanPayAddPayReq")
	proto.RegisterType((*ScanPayAddPayResp)(nil), "zqbapis.ScanPayAddPayResp")
}

func init() { proto.RegisterFile("scanpay.proto", fileDescriptor_e620eaf8bd5845ef) }

var fileDescriptor_e620eaf8bd5845ef = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd0, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x70, 0x25, 0x88, 0x54, 0x1c, 0x50, 0xc0, 0x43, 0xc9, 0x58, 0x3c, 0x95, 0x85, 0x85,
	0x27, 0x40, 0xbc, 0x40, 0x65, 0xd8, 0x40, 0xaa, 0xae, 0xb9, 0x1b, 0x2c, 0xe4, 0xf8, 0xcf, 0x39,
	0x82, 0xf0, 0xf4, 0x28, 0xc1, 0x0c, 0x30, 0xa0, 0x4e, 0xd6, 0x67, 0x7d, 0xf7, 0xd3, 0xe9, 0xe0,
	0x5c, 0x3a, 0xec, 0x03, 0x8e, 0x77, 0x21, 0xf9, 0xec, 0xd5, 0xe2, 0x33, 0xee, 0x31, 0x58, 0xd1,
	0xb7, 0xb0, 0x7c, 0xea, 0xb0, 0xdf, 0xe2, 0x38, 0x3d, 0x86, 0xa3, 0xba, 0x86, 0x45, 0x4c, 0xbb,
	0xce, 0x13, 0xb7, 0xd5, 0xba, 0xda, 0x9c, 0x98, 0x26, 0xa6, 0x47, 0x4f, 0xac, 0x5f, 0xe1, 0xe2,
	0x57, 0x55, 0x82, 0x5a, 0x42, 0x6d, 0xa9, 0xd4, 0x6a, 0x4b, 0x6a, 0x05, 0x0d, 0x3a, 0x3f, 0xf4,
	0xb9, 0xad, 0xd7, 0xd5, 0xa6, 0x32, 0x25, 0xa9, 0x1b, 0x38, 0xe3, 0x8f, 0x60, 0x13, 0xd3, 0x2e,
	0x5b, 0xc7, 0xed, 0xd1, 0x3c, 0x71, 0x5a, 0xfe, 0x9e, 0xad, 0x63, 0x6d, 0xe0, 0xb2, 0xe8, 0x0f,
	0x44, 0x5b, 0x1c, 0xa7, 0x55, 0x0e, 0xe5, 0x57, 0xd0, 0x04, 0x14, 0x79, 0xa7, 0x02, 0x97, 0xa4,
	0x5f, 0xe0, 0xea, 0x8f, 0x29, 0x61, 0x2a, 0x4b, 0xc6, 0x3c, 0xc8, 0x0c, 0x1f, 0x9b, 0x92, 0xfe,
	0xc3, 0x13, 0x3b, 0x4c, 0x6f, 0x3f, 0xf8, 0x77, 0xda, 0x37, 0xf3, 0x25, 0xef, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x4e, 0x11, 0xac, 0x72, 0x5a, 0x01, 0x00, 0x00,
}
