// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: securitypasswd.proto

package zqbapis

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SecurityPasswdUpdateType_Enum int32

const (
	// 首次新增密碼
	SecurityPasswdUpdateType_FirstToAdd SecurityPasswdUpdateType_Enum = 0
	// 驗證成功更新密碼
	SecurityPasswdUpdateType_UpdatePwd SecurityPasswdUpdateType_Enum = 1
	// 忘記密碼更新
	SecurityPasswdUpdateType_ForgetToUpdate SecurityPasswdUpdateType_Enum = 2
)

var SecurityPasswdUpdateType_Enum_name = map[int32]string{
	0: "FirstToAdd",
	1: "UpdatePwd",
	2: "ForgetToUpdate",
}

var SecurityPasswdUpdateType_Enum_value = map[string]int32{
	"FirstToAdd":     0,
	"UpdatePwd":      1,
	"ForgetToUpdate": 2,
}

func (x SecurityPasswdUpdateType_Enum) String() string {
	return proto.EnumName(SecurityPasswdUpdateType_Enum_name, int32(x))
}

func (SecurityPasswdUpdateType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{4, 0}
}

// 修改安全密碼
type SecurityPasswdUpdateReq struct {
	//更新方式
	Type SecurityPasswdUpdateType_Enum `protobuf:"varint,1,opt,name=type,proto3,enum=zqbapis.SecurityPasswdUpdateType_Enum" json:"type,omitempty"`
	// 密碼
	Passwd string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	// 新密碼
	NewPasswd string `protobuf:"bytes,3,opt,name=new_passwd,json=newPasswd,proto3" json:"new_passwd,omitempty"`
	// 忘記密碼：修改密碼要用的 Token
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdUpdateReq) Reset()         { *m = SecurityPasswdUpdateReq{} }
func (m *SecurityPasswdUpdateReq) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdUpdateReq) ProtoMessage()    {}
func (*SecurityPasswdUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{0}
}
func (m *SecurityPasswdUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdUpdateReq.Unmarshal(m, b)
}
func (m *SecurityPasswdUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdUpdateReq.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdUpdateReq.Merge(m, src)
}
func (m *SecurityPasswdUpdateReq) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdUpdateReq.Size(m)
}
func (m *SecurityPasswdUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdUpdateReq proto.InternalMessageInfo

func (m *SecurityPasswdUpdateReq) GetType() SecurityPasswdUpdateType_Enum {
	if m != nil {
		return m.Type
	}
	return SecurityPasswdUpdateType_FirstToAdd
}

func (m *SecurityPasswdUpdateReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *SecurityPasswdUpdateReq) GetNewPasswd() string {
	if m != nil {
		return m.NewPasswd
	}
	return ""
}

func (m *SecurityPasswdUpdateReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 修改安全密碼回應
type SecurityPasswdUpdateResp struct {
	// 狀態 0=失敗 1=成功
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdUpdateResp) Reset()         { *m = SecurityPasswdUpdateResp{} }
func (m *SecurityPasswdUpdateResp) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdUpdateResp) ProtoMessage()    {}
func (*SecurityPasswdUpdateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{1}
}
func (m *SecurityPasswdUpdateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdUpdateResp.Unmarshal(m, b)
}
func (m *SecurityPasswdUpdateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdUpdateResp.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdUpdateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdUpdateResp.Merge(m, src)
}
func (m *SecurityPasswdUpdateResp) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdUpdateResp.Size(m)
}
func (m *SecurityPasswdUpdateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdUpdateResp.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdUpdateResp proto.InternalMessageInfo

func (m *SecurityPasswdUpdateResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 忘記安全密碼
type SecurityPasswdForgetReq struct {
	// 手機號碼(ex:15229067700)
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// qq account
	QqAccount string `protobuf:"bytes,2,opt,name=qq_account,json=qqAccount,proto3" json:"qq_account,omitempty"`
	// chinese name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 登入密碼
	LoginPasswd          string   `protobuf:"bytes,4,opt,name=login_passwd,json=loginPasswd,proto3" json:"login_passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdForgetReq) Reset()         { *m = SecurityPasswdForgetReq{} }
func (m *SecurityPasswdForgetReq) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdForgetReq) ProtoMessage()    {}
func (*SecurityPasswdForgetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{2}
}
func (m *SecurityPasswdForgetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdForgetReq.Unmarshal(m, b)
}
func (m *SecurityPasswdForgetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdForgetReq.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdForgetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdForgetReq.Merge(m, src)
}
func (m *SecurityPasswdForgetReq) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdForgetReq.Size(m)
}
func (m *SecurityPasswdForgetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdForgetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdForgetReq proto.InternalMessageInfo

func (m *SecurityPasswdForgetReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SecurityPasswdForgetReq) GetQqAccount() string {
	if m != nil {
		return m.QqAccount
	}
	return ""
}

func (m *SecurityPasswdForgetReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SecurityPasswdForgetReq) GetLoginPasswd() string {
	if m != nil {
		return m.LoginPasswd
	}
	return ""
}

// 忘記安全密碼驗證結果
type SecurityPasswdForgetResp struct {
	// 狀態 0=失敗 1=成功
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 密碼金鑰
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdForgetResp) Reset()         { *m = SecurityPasswdForgetResp{} }
func (m *SecurityPasswdForgetResp) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdForgetResp) ProtoMessage()    {}
func (*SecurityPasswdForgetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{3}
}
func (m *SecurityPasswdForgetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdForgetResp.Unmarshal(m, b)
}
func (m *SecurityPasswdForgetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdForgetResp.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdForgetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdForgetResp.Merge(m, src)
}
func (m *SecurityPasswdForgetResp) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdForgetResp.Size(m)
}
func (m *SecurityPasswdForgetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdForgetResp.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdForgetResp proto.InternalMessageInfo

func (m *SecurityPasswdForgetResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SecurityPasswdForgetResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SecurityPasswdUpdateType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdUpdateType) Reset()         { *m = SecurityPasswdUpdateType{} }
func (m *SecurityPasswdUpdateType) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdUpdateType) ProtoMessage()    {}
func (*SecurityPasswdUpdateType) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{4}
}
func (m *SecurityPasswdUpdateType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdUpdateType.Unmarshal(m, b)
}
func (m *SecurityPasswdUpdateType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdUpdateType.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdUpdateType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdUpdateType.Merge(m, src)
}
func (m *SecurityPasswdUpdateType) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdUpdateType.Size(m)
}
func (m *SecurityPasswdUpdateType) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdUpdateType.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdUpdateType proto.InternalMessageInfo

// 是否首次使用安全密碼
type SecurityPasswdFirstUseResp struct {
	// 狀態 0=非首次 1=首次
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdFirstUseResp) Reset()         { *m = SecurityPasswdFirstUseResp{} }
func (m *SecurityPasswdFirstUseResp) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdFirstUseResp) ProtoMessage()    {}
func (*SecurityPasswdFirstUseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{5}
}
func (m *SecurityPasswdFirstUseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdFirstUseResp.Unmarshal(m, b)
}
func (m *SecurityPasswdFirstUseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdFirstUseResp.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdFirstUseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdFirstUseResp.Merge(m, src)
}
func (m *SecurityPasswdFirstUseResp) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdFirstUseResp.Size(m)
}
func (m *SecurityPasswdFirstUseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdFirstUseResp.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdFirstUseResp proto.InternalMessageInfo

func (m *SecurityPasswdFirstUseResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//檢查安全密碼是否正確
type SecurityPasswdIdentifierReq struct {
	// 安全密碼
	Passwd               string   `protobuf:"bytes,1,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdIdentifierReq) Reset()         { *m = SecurityPasswdIdentifierReq{} }
func (m *SecurityPasswdIdentifierReq) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdIdentifierReq) ProtoMessage()    {}
func (*SecurityPasswdIdentifierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{6}
}
func (m *SecurityPasswdIdentifierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdIdentifierReq.Unmarshal(m, b)
}
func (m *SecurityPasswdIdentifierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdIdentifierReq.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdIdentifierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdIdentifierReq.Merge(m, src)
}
func (m *SecurityPasswdIdentifierReq) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdIdentifierReq.Size(m)
}
func (m *SecurityPasswdIdentifierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdIdentifierReq.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdIdentifierReq proto.InternalMessageInfo

func (m *SecurityPasswdIdentifierReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SecurityPasswdIdentifierResp struct {
	// 密碼金鑰
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityPasswdIdentifierResp) Reset()         { *m = SecurityPasswdIdentifierResp{} }
func (m *SecurityPasswdIdentifierResp) String() string { return proto.CompactTextString(m) }
func (*SecurityPasswdIdentifierResp) ProtoMessage()    {}
func (*SecurityPasswdIdentifierResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_757670919b81cc81, []int{7}
}
func (m *SecurityPasswdIdentifierResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityPasswdIdentifierResp.Unmarshal(m, b)
}
func (m *SecurityPasswdIdentifierResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityPasswdIdentifierResp.Marshal(b, m, deterministic)
}
func (m *SecurityPasswdIdentifierResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityPasswdIdentifierResp.Merge(m, src)
}
func (m *SecurityPasswdIdentifierResp) XXX_Size() int {
	return xxx_messageInfo_SecurityPasswdIdentifierResp.Size(m)
}
func (m *SecurityPasswdIdentifierResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityPasswdIdentifierResp.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityPasswdIdentifierResp proto.InternalMessageInfo

func (m *SecurityPasswdIdentifierResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("zqbapis.SecurityPasswdUpdateType_Enum", SecurityPasswdUpdateType_Enum_name, SecurityPasswdUpdateType_Enum_value)
	proto.RegisterType((*SecurityPasswdUpdateReq)(nil), "zqbapis.SecurityPasswdUpdateReq")
	proto.RegisterType((*SecurityPasswdUpdateResp)(nil), "zqbapis.SecurityPasswdUpdateResp")
	proto.RegisterType((*SecurityPasswdForgetReq)(nil), "zqbapis.SecurityPasswdForgetReq")
	proto.RegisterType((*SecurityPasswdForgetResp)(nil), "zqbapis.SecurityPasswdForgetResp")
	proto.RegisterType((*SecurityPasswdUpdateType)(nil), "zqbapis.SecurityPasswdUpdateType")
	proto.RegisterType((*SecurityPasswdFirstUseResp)(nil), "zqbapis.SecurityPasswdFirstUseResp")
	proto.RegisterType((*SecurityPasswdIdentifierReq)(nil), "zqbapis.SecurityPasswdIdentifierReq")
	proto.RegisterType((*SecurityPasswdIdentifierResp)(nil), "zqbapis.SecurityPasswdIdentifierResp")
}

func init() { proto.RegisterFile("securitypasswd.proto", fileDescriptor_757670919b81cc81) }

var fileDescriptor_757670919b81cc81 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4d, 0x4f, 0xc2, 0x30,
	0x18, 0xc7, 0x2d, 0x0e, 0xcc, 0x1e, 0x95, 0x90, 0x86, 0xe0, 0xe2, 0x4b, 0x82, 0x3d, 0x18, 0x4e,
	0x3b, 0x20, 0x1e, 0xf4, 0xc6, 0x41, 0xa2, 0x37, 0x32, 0xe1, 0x4c, 0x06, 0xab, 0xa4, 0x11, 0xda,
	0x6e, 0xed, 0xb2, 0xe0, 0x17, 0xf0, 0x7b, 0xf8, 0x49, 0xcd, 0xda, 0x12, 0x10, 0xc1, 0x5b, 0x9f,
	0xb7, 0x3e, 0xbf, 0xff, 0x3f, 0x0f, 0x34, 0x15, 0x9d, 0xe5, 0x19, 0xd3, 0x2b, 0x19, 0x2b, 0x55,
	0x24, 0xa1, 0xcc, 0x84, 0x16, 0xf8, 0xe4, 0x33, 0x9d, 0xc6, 0x92, 0x29, 0xf2, 0x8d, 0xe0, 0xe2,
	0xcd, 0x75, 0x0c, 0x4d, 0xc7, 0x58, 0x26, 0xb1, 0xa6, 0x11, 0x4d, 0xf1, 0x13, 0x78, 0x7a, 0x25,
	0x69, 0x80, 0xda, 0xa8, 0x53, 0xef, 0xde, 0x85, 0x6e, 0x26, 0xdc, 0xd7, 0x3f, 0x5a, 0x49, 0x1a,
	0x3e, 0xf3, 0x7c, 0x19, 0x99, 0x19, 0xdc, 0x82, 0x9a, 0x5d, 0x18, 0x54, 0xda, 0xa8, 0xe3, 0x47,
	0x2e, 0xc2, 0x37, 0x00, 0x9c, 0x16, 0x13, 0x57, 0x3b, 0x36, 0x35, 0x9f, 0xd3, 0xc2, 0xfe, 0x85,
	0x9b, 0x50, 0xd5, 0xe2, 0x83, 0xf2, 0xc0, 0x33, 0x15, 0x1b, 0x90, 0x2e, 0x04, 0xfb, 0x19, 0x95,
	0x2c, 0x17, 0x29, 0x1d, 0xeb, 0x5c, 0x19, 0xcc, 0x6a, 0xe4, 0x22, 0xf2, 0xf5, 0x47, 0xd8, 0x40,
	0x64, 0x73, 0xaa, 0x4b, 0x61, 0x2d, 0xa8, 0x2d, 0xc5, 0x94, 0x2d, 0xac, 0x34, 0x3f, 0x72, 0x51,
	0x09, 0x97, 0xa6, 0x93, 0x78, 0x36, 0x13, 0x39, 0xd7, 0x0e, 0xdc, 0x4f, 0xd3, 0xbe, 0x4d, 0x60,
	0x0c, 0x1e, 0x8f, 0x97, 0xd4, 0x51, 0x9b, 0x37, 0xbe, 0x85, 0xb3, 0x85, 0x98, 0x33, 0xbe, 0x56,
	0x64, 0xb9, 0x4f, 0x4d, 0xce, 0xae, 0x25, 0x2f, 0xbb, 0xf4, 0x6b, 0x90, 0xc3, 0xf4, 0x1b, 0x1f,
	0x2a, 0xdb, 0x3e, 0x8c, 0xf7, 0xfb, 0x50, 0x7a, 0x4f, 0x1e, 0xc1, 0x2b, 0xed, 0xc7, 0x75, 0x80,
	0x01, 0xcb, 0x94, 0x1e, 0x89, 0x7e, 0x92, 0x34, 0x8e, 0xf0, 0x39, 0xf8, 0xb6, 0x6b, 0x58, 0x24,
	0x0d, 0x84, 0x31, 0xd4, 0xed, 0xfa, 0x91, 0xb0, 0xe9, 0x46, 0x85, 0xf4, 0xe0, 0x72, 0x07, 0xb0,
	0xfc, 0x60, 0xac, 0xfe, 0x37, 0xf8, 0x01, 0xae, 0x7e, 0x4f, 0xbd, 0x26, 0x94, 0x6b, 0xf6, 0xce,
	0x68, 0xe6, 0x3c, 0x76, 0x96, 0xa0, 0xed, 0x03, 0x20, 0x3d, 0xb8, 0x3e, 0x3c, 0xa6, 0xe4, 0x46,
	0x39, 0xda, 0x52, 0x3e, 0xad, 0x99, 0xb3, 0xbd, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x2c,
	0x7c, 0xfe, 0xce, 0x02, 0x00, 0x00,
}
