// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction.proto

package zqbapis

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransactionClassType_Enum int32

const (
	TransactionClassType_All            TransactionClassType_Enum = 0
	TransactionClassType_Deposit        TransactionClassType_Enum = 3
	TransactionClassType_Scanpay        TransactionClassType_Enum = 4
	TransactionClassType_ReceivePayment TransactionClassType_Enum = 5
)

var TransactionClassType_Enum_name = map[int32]string{
	0: "All",
	3: "Deposit",
	4: "Scanpay",
	5: "ReceivePayment",
}

var TransactionClassType_Enum_value = map[string]int32{
	"All":            0,
	"Deposit":        3,
	"Scanpay":        4,
	"ReceivePayment": 5,
}

func (x TransactionClassType_Enum) String() string {
	return proto.EnumName(TransactionClassType_Enum_name, int32(x))
}

func (TransactionClassType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3, 0}
}

// 交易流水請求
type TransactionReq struct {
	Paging               *Paging                   `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Class                TransactionClassType_Enum `protobuf:"varint,2,opt,name=class,proto3,enum=zqbapis.TransactionClassType_Enum" json:"class,omitempty" form:"class"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TransactionReq) Reset()         { *m = TransactionReq{} }
func (m *TransactionReq) String() string { return proto.CompactTextString(m) }
func (*TransactionReq) ProtoMessage()    {}
func (*TransactionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}
func (m *TransactionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReq.Unmarshal(m, b)
}
func (m *TransactionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReq.Marshal(b, m, deterministic)
}
func (m *TransactionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReq.Merge(m, src)
}
func (m *TransactionReq) XXX_Size() int {
	return xxx_messageInfo_TransactionReq.Size(m)
}
func (m *TransactionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReq proto.InternalMessageInfo

func (m *TransactionReq) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *TransactionReq) GetClass() TransactionClassType_Enum {
	if m != nil {
		return m.Class
	}
	return TransactionClassType_All
}

// 交易流水列表結果
type TransactionListResp struct {
	Paging               *PagingResult      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Data                 []*TransactionList `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionListResp) Reset()         { *m = TransactionListResp{} }
func (m *TransactionListResp) String() string { return proto.CompactTextString(m) }
func (*TransactionListResp) ProtoMessage()    {}
func (*TransactionListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}
func (m *TransactionListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionListResp.Unmarshal(m, b)
}
func (m *TransactionListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionListResp.Marshal(b, m, deterministic)
}
func (m *TransactionListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionListResp.Merge(m, src)
}
func (m *TransactionListResp) XXX_Size() int {
	return xxx_messageInfo_TransactionListResp.Size(m)
}
func (m *TransactionListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionListResp.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionListResp proto.InternalMessageInfo

func (m *TransactionListResp) GetPaging() *PagingResult {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *TransactionListResp) GetData() []*TransactionList {
	if m != nil {
		return m.Data
	}
	return nil
}

// 交易流水詳情結果
type TransactionDetailResp struct {
	Data                 *TransactionDetail `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionDetailResp) Reset()         { *m = TransactionDetailResp{} }
func (m *TransactionDetailResp) String() string { return proto.CompactTextString(m) }
func (*TransactionDetailResp) ProtoMessage()    {}
func (*TransactionDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}
func (m *TransactionDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionDetailResp.Unmarshal(m, b)
}
func (m *TransactionDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionDetailResp.Marshal(b, m, deterministic)
}
func (m *TransactionDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionDetailResp.Merge(m, src)
}
func (m *TransactionDetailResp) XXX_Size() int {
	return xxx_messageInfo_TransactionDetailResp.Size(m)
}
func (m *TransactionDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionDetailResp proto.InternalMessageInfo

func (m *TransactionDetailResp) GetData() *TransactionDetail {
	if m != nil {
		return m.Data
	}
	return nil
}

// 交易流水來源
type TransactionClassType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionClassType) Reset()         { *m = TransactionClassType{} }
func (m *TransactionClassType) String() string { return proto.CompactTextString(m) }
func (*TransactionClassType) ProtoMessage()    {}
func (*TransactionClassType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}
func (m *TransactionClassType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionClassType.Unmarshal(m, b)
}
func (m *TransactionClassType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionClassType.Marshal(b, m, deterministic)
}
func (m *TransactionClassType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionClassType.Merge(m, src)
}
func (m *TransactionClassType) XXX_Size() int {
	return xxx_messageInfo_TransactionClassType.Size(m)
}
func (m *TransactionClassType) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionClassType.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionClassType proto.InternalMessageInfo

// 交易流水列表
type TransactionList struct {
	// 編號
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 類別
	Class string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	// 來源
	SourceType string `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// 金額
	Amount float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 變動後可用餘額
	ChangedBalance float64 `protobuf:"fixed64,5,opt,name=changed_balance,json=changedBalance,proto3" json:"changed_balance,omitempty"`
	// 時間
	AddedTime string `protobuf:"bytes,6,opt,name=added_time,json=addedTime,proto3" json:"added_time,omitempty"`
	// 品牌名稱
	BrandName            string   `protobuf:"bytes,7,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionList) Reset()         { *m = TransactionList{} }
func (m *TransactionList) String() string { return proto.CompactTextString(m) }
func (*TransactionList) ProtoMessage()    {}
func (*TransactionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}
func (m *TransactionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionList.Unmarshal(m, b)
}
func (m *TransactionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionList.Marshal(b, m, deterministic)
}
func (m *TransactionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionList.Merge(m, src)
}
func (m *TransactionList) XXX_Size() int {
	return xxx_messageInfo_TransactionList.Size(m)
}
func (m *TransactionList) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionList.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionList proto.InternalMessageInfo

func (m *TransactionList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionList) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *TransactionList) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *TransactionList) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionList) GetChangedBalance() float64 {
	if m != nil {
		return m.ChangedBalance
	}
	return 0
}

func (m *TransactionList) GetAddedTime() string {
	if m != nil {
		return m.AddedTime
	}
	return ""
}

func (m *TransactionList) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

// 交易流水詳情
type TransactionDetail struct {
	// 編號
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 會員編號
	MemberId string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// 來源
	SourceType string `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// 來源id
	SourceId string `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// 金額
	Amount float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// 原資產
	CurrentTotalAmount float64 `protobuf:"fixed64,6,opt,name=current_total_amount,json=currentTotalAmount,proto3" json:"current_total_amount,omitempty"`
	// 變動後資產
	ChangedTotalAmount float64 `protobuf:"fixed64,7,opt,name=changed_total_amount,json=changedTotalAmount,proto3" json:"changed_total_amount,omitempty"`
	// 原可用餘額
	CurrentBalance float64 `protobuf:"fixed64,8,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	// 變動後可用餘額
	ChangedBalance float64 `protobuf:"fixed64,9,opt,name=changed_balance,json=changedBalance,proto3" json:"changed_balance,omitempty"`
	// 時間
	AddedTime string `protobuf:"bytes,10,opt,name=added_time,json=addedTime,proto3" json:"added_time,omitempty"`
	// 備註
	Remarks string `protobuf:"bytes,11,opt,name=remarks,proto3" json:"remarks,omitempty"`
	// 銀行名稱
	BankName string `protobuf:"bytes,12,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	// 銀行卡號
	CardNumber           string   `protobuf:"bytes,13,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionDetail) Reset()         { *m = TransactionDetail{} }
func (m *TransactionDetail) String() string { return proto.CompactTextString(m) }
func (*TransactionDetail) ProtoMessage()    {}
func (*TransactionDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}
func (m *TransactionDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionDetail.Unmarshal(m, b)
}
func (m *TransactionDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionDetail.Marshal(b, m, deterministic)
}
func (m *TransactionDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionDetail.Merge(m, src)
}
func (m *TransactionDetail) XXX_Size() int {
	return xxx_messageInfo_TransactionDetail.Size(m)
}
func (m *TransactionDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionDetail proto.InternalMessageInfo

func (m *TransactionDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionDetail) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *TransactionDetail) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *TransactionDetail) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *TransactionDetail) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionDetail) GetCurrentTotalAmount() float64 {
	if m != nil {
		return m.CurrentTotalAmount
	}
	return 0
}

func (m *TransactionDetail) GetChangedTotalAmount() float64 {
	if m != nil {
		return m.ChangedTotalAmount
	}
	return 0
}

func (m *TransactionDetail) GetCurrentBalance() float64 {
	if m != nil {
		return m.CurrentBalance
	}
	return 0
}

func (m *TransactionDetail) GetChangedBalance() float64 {
	if m != nil {
		return m.ChangedBalance
	}
	return 0
}

func (m *TransactionDetail) GetAddedTime() string {
	if m != nil {
		return m.AddedTime
	}
	return ""
}

func (m *TransactionDetail) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *TransactionDetail) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *TransactionDetail) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func init() {
	proto.RegisterEnum("zqbapis.TransactionClassType_Enum", TransactionClassType_Enum_name, TransactionClassType_Enum_value)
	proto.RegisterType((*TransactionReq)(nil), "zqbapis.TransactionReq")
	proto.RegisterType((*TransactionListResp)(nil), "zqbapis.TransactionListResp")
	proto.RegisterType((*TransactionDetailResp)(nil), "zqbapis.TransactionDetailResp")
	proto.RegisterType((*TransactionClassType)(nil), "zqbapis.TransactionClassType")
	proto.RegisterType((*TransactionList)(nil), "zqbapis.TransactionList")
	proto.RegisterType((*TransactionDetail)(nil), "zqbapis.TransactionDetail")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0xad, 0xf3, 0xe1, 0xe0, 0x09, 0x0d, 0x66, 0x0b, 0x95, 0x05, 0xaa, 0x88, 0x7c, 0x21, 0x87,
	0x12, 0x2a, 0x7a, 0xeb, 0x0d, 0x4a, 0x55, 0x51, 0xb5, 0x08, 0x99, 0xdc, 0xad, 0xb5, 0x3d, 0x84,
	0x55, 0xbc, 0x6b, 0x63, 0xaf, 0x2b, 0xa5, 0x52, 0x8f, 0xfd, 0x65, 0xfd, 0x11, 0xbd, 0xf5, 0x47,
	0xf4, 0x17, 0x54, 0xfb, 0x11, 0x08, 0x21, 0x52, 0x7b, 0xf3, 0xbc, 0xf7, 0x66, 0x66, 0xdf, 0x1b,
	0xc9, 0xb0, 0x2d, 0x2b, 0x2a, 0x6a, 0x9a, 0x4a, 0x56, 0x88, 0x71, 0x59, 0x15, 0xb2, 0x20, 0xbd,
	0x6f, 0x77, 0x09, 0x2d, 0x59, 0xbd, 0xb7, 0x99, 0x16, 0x9c, 0x2f, 0xe0, 0xbd, 0xa3, 0x29, 0x93,
	0xb7, 0x4d, 0x32, 0x4e, 0x0b, 0x7e, 0x3c, 0x2d, 0xa6, 0xc5, 0xb1, 0x86, 0x93, 0xe6, 0x46, 0x57,
	0xba, 0xd0, 0x5f, 0x46, 0x1e, 0xfe, 0x70, 0x60, 0x30, 0x79, 0x98, 0x1d, 0xe1, 0x1d, 0x39, 0x04,
	0xb7, 0xa4, 0x53, 0x26, 0xa6, 0x81, 0x33, 0x74, 0x46, 0xfd, 0x93, 0xad, 0xb1, 0xdd, 0x34, 0xbe,
	0xd2, 0x70, 0x64, 0x69, 0xf2, 0x09, 0xba, 0x69, 0x4e, 0xeb, 0x3a, 0x68, 0x0d, 0x9d, 0xd1, 0xe0,
	0x24, 0xbc, 0xd7, 0x2d, 0x0d, 0x7c, 0xaf, 0x04, 0x93, 0x79, 0x89, 0xe3, 0x0f, 0xa2, 0xe1, 0x67,
	0xfe, 0x9f, 0xdf, 0x07, 0x9b, 0x37, 0x45, 0xc5, 0xdf, 0x85, 0xba, 0x35, 0x8c, 0xcc, 0x88, 0xb0,
	0x82, 0x17, 0x4b, 0x5d, 0x9f, 0x59, 0x2d, 0x23, 0xac, 0x4b, 0x72, 0xb4, 0xf2, 0x96, 0xdd, 0xd5,
	0xb7, 0x60, 0xdd, 0xe4, 0xf2, 0xfe, 0x45, 0xaf, 0xa1, 0x93, 0x51, 0x49, 0x83, 0xd6, 0xb0, 0x3d,
	0xea, 0x9f, 0x04, 0xeb, 0x1e, 0xa4, 0x47, 0x6b, 0x55, 0xf8, 0x11, 0x76, 0x97, 0x88, 0x73, 0x94,
	0x94, 0xe5, 0x7a, 0xeb, 0xd8, 0x8e, 0x31, 0x3b, 0xf7, 0xd6, 0x8d, 0xb1, 0x6a, 0x33, 0xe8, 0x3b,
	0xec, 0xac, 0xb3, 0x1c, 0x22, 0x74, 0x94, 0x6b, 0xd2, 0x83, 0xf6, 0x69, 0x9e, 0xfb, 0xcf, 0x08,
	0x80, 0x7b, 0x45, 0x8b, 0x1b, 0x14, 0xbe, 0xa3, 0xbe, 0xbf, 0xd0, 0x6a, 0x86, 0xd2, 0x6f, 0x91,
	0x3e, 0xf4, 0xce, 0xb1, 0x2c, 0x6a, 0x26, 0xfd, 0xb6, 0x2a, 0xae, 0x53, 0x2a, 0x4a, 0x3a, 0xf7,
	0x3b, 0x84, 0xc0, 0x20, 0xc2, 0x14, 0xd9, 0x57, 0xbc, 0xa2, 0x73, 0x8e, 0x42, 0xfa, 0x5d, 0x32,
	0x00, 0x30, 0x9d, 0xd7, 0x98, 0xe7, 0xbe, 0x1b, 0xfe, 0x72, 0x60, 0x6b, 0xc5, 0x21, 0x19, 0x40,
	0x8b, 0x65, 0xda, 0x80, 0x17, 0xb5, 0x58, 0x46, 0x76, 0x96, 0x6f, 0xe5, 0xd9, 0xd4, 0xc9, 0x01,
	0xf4, 0xeb, 0xa2, 0xa9, 0x52, 0x8c, 0xe5, 0xbc, 0xc4, 0xa0, 0xad, 0x39, 0x30, 0x90, 0x72, 0x40,
	0x5e, 0x82, 0x4b, 0x79, 0xd1, 0x08, 0x19, 0x74, 0x86, 0xce, 0xc8, 0x89, 0x6c, 0x45, 0x0e, 0x61,
	0x2b, 0xbd, 0xa5, 0x62, 0x8a, 0x59, 0x9c, 0xd0, 0x9c, 0x8a, 0x14, 0x83, 0xae, 0x16, 0x0c, 0x2c,
	0x7c, 0x66, 0x50, 0xf2, 0x0a, 0x80, 0x66, 0x19, 0x66, 0xb1, 0x64, 0x1c, 0x03, 0x57, 0x2f, 0xf0,
	0x34, 0x32, 0x61, 0x5c, 0xd3, 0x49, 0x45, 0x45, 0x16, 0x0b, 0xca, 0x31, 0xe8, 0x19, 0x5a, 0x23,
	0x97, 0x94, 0x63, 0xf8, 0xb3, 0x0d, 0xdb, 0x4f, 0x42, 0x7f, 0xe2, 0x6d, 0x1f, 0x3c, 0x8e, 0x3c,
	0xc1, 0x2a, 0x66, 0x99, 0xf5, 0xb7, 0x61, 0x80, 0x8b, 0xec, 0xdf, 0x16, 0xf7, 0xc1, 0xb3, 0x02,
	0x96, 0x69, 0x97, 0x5e, 0xb4, 0x61, 0x80, 0x8b, 0x6c, 0xc9, 0x7f, 0xf7, 0x91, 0xff, 0x37, 0xb0,
	0x93, 0x36, 0x55, 0x85, 0x42, 0xc6, 0xb2, 0x90, 0x34, 0x8f, 0xad, 0xca, 0xd5, 0x2a, 0x62, 0xb9,
	0x89, 0xa2, 0x4e, 0x1f, 0x3a, 0x6c, 0x62, 0x8f, 0x3a, 0x7a, 0xb6, 0xc3, 0x70, 0xcb, 0x1d, 0x2a,
	0x63, 0xbb, 0x63, 0x91, 0xf1, 0x86, 0xcd, 0xd8, 0xc0, 0x8b, 0x8c, 0xd7, 0x1c, 0xc3, 0xfb, 0x8f,
	0x63, 0xc0, 0xea, 0x31, 0x02, 0xe8, 0x55, 0xc8, 0x69, 0x35, 0xab, 0x83, 0xbe, 0xe6, 0x16, 0xa5,
	0xca, 0x28, 0xa1, 0x62, 0x66, 0xae, 0xb4, 0x69, 0x32, 0x52, 0x80, 0x3a, 0x92, 0x4a, 0x38, 0xa5,
	0x55, 0x16, 0x8b, 0x46, 0x45, 0x1e, 0x3c, 0x37, 0x09, 0x2b, 0xe8, 0x52, 0x23, 0x89, 0xab, 0x7f,
	0x35, 0x6f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x8d, 0xe4, 0x64, 0xc5, 0x04, 0x00, 0x00,
}
